### ISSUE TITLE
Bug: border is not show correctly in new card input form

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5405] opened 2022-02-14 12:53 UTC
## Description and expectations

When I create a new card in app-kanban I can see border in red when I wrote text. But the red border size not corresponding to input form.

### How to reproduce

Create a new colum.

### Version information

- Tracim version: 4.1.0 build_68
- Web browser: Firefox
- Version: 96
- Device / System: Ubuntu 20.04

### Screenshots

https://user-images.githubusercontent.com/25848257/153867952-37c20591-908b-4803-b730-be17a717c35e.mp4

________________________________________________

**Comment by buxx** [comment] 2022-09-06 12:16
Taken for the "one hour" technical event.

**Comment by buxx** [comment] 2022-09-06 12:51
Can't reproduce with Ubuntu 20.04 and firefox 104.0. @PhilippeAccorsi Can you try again and indicate if bug is still here ?

**Comment by PhilippeAccorsi** [comment] 2022-09-06 12:59
Firefox 104 is it the last version on stable ubuntu ? (not backported version)
If yes we can close this issue I think.
If no, I think we need to test with the last stable available on Ubuntu20.04

**Comment by Quiwy** [comment] 2022-09-06 13:34
Firefox 104 is the latest version on ubuntu 20.04 https://packages.ubuntu.com/focal/firefox :smile: 

Closing the issue

**Closed by Quiwy** 2022-09-06 13:34 UTC
Labels: app-kanban
