### ISSUE TITLE
npm warning about depracated package when running install_frontend_dependencies.sh

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2769] opened 2020-03-18 22:31 UTC
## Bug description & symptom

When I build Tracim docker image, I can see many warning appear when `install_frontend_dependencies.sh` is running:

~~~
[22:01:04] $ npm i
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> core-js@3.6.4 postinstall /tracim/frontend_app_agenda/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN tracim_app_agenda@1.0.0 No description
npm WARN tracim_app_agenda@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules/fsevents/node_modules/abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/abbrev' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules/fsevents/node_modules/ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/ansi-regex' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules/fsevents/node_modules/aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/aproba' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules/fsevents/node_modules/balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/balanced-match' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.3 (node_modules/fsevents/node_modules/chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/chownr' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules/fsevents/node_modules/code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/code-point-at' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules/fsevents/node_modules/concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/concat-map' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules/fsevents/node_modules/console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/console-control-strings' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules/fsevents/node_modules/core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/core-util-is' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules/fsevents/node_modules/deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/deep-extend' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules/fsevents/node_modules/delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/delegates' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules/fsevents/node_modules/detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/detect-libc' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules/fsevents/node_modules/fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/fs.realpath' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules/fsevents/node_modules/has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/has-unicode' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules/fsevents/node_modules/inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/inherits' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules/fsevents/node_modules/ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/ini' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules/fsevents/node_modules/isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/isarray' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@0.0.8 (node_modules/fsevents/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/minimist' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules/fsevents/node_modules/ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/ms' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules/fsevents/node_modules/npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/npm-normalize-package-bin' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules/fsevents/node_modules/number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/number-is-nan' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules/fsevents/node_modules/object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/object-assign' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules/fsevents/node_modules/os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/os-homedir' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules/fsevents/node_modules/os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/os-tmpdir' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules/fsevents/node_modules/path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/path-is-absolute' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules/fsevents/node_modules/process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/process-nextick-args' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules/fsevents/node_modules/rc/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/rc/node_modules/minimist' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/rc/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules/fsevents/node_modules/safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/safe-buffer' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules/fsevents/node_modules/safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/safer-buffer' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules/fsevents/node_modules/sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/sax' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules/fsevents/node_modules/semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/semver' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.semver.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules/fsevents/node_modules/set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/set-blocking' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules/fsevents/node_modules/signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/signal-exit' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules/fsevents/node_modules/strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/strip-json-comments' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules/fsevents/node_modules/util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/util-deprecate' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules/fsevents/node_modules/wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/wrappy' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules/fsevents/node_modules/yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/yallist' -> '/tracim/frontend_app_agenda/node_modules/fsevents/node_modules/.yallist.DELETE'
~~~

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] not use deprecated package in tracim or find a way to explicit thats its normal.

## Context and version information

- fresh install of tracim (2.6.3) in local folder
- Visible when I build Tracim docker image of 2.6.2_rc1 version.

## Prerequisites

- create list of all package need to be updated

## How to reproduce

- fresh install of tracim (2.6.3) in local folder
- Visible when I build Tracim docker image of 2.6.2_rc1 version.
- visible on two server: 
  - Docker version 19.03.7, build 7141c199a2 (on Debian 10 Buster)
  - Docker version 18.09.1, build 4c52b90 (on Debian 9 Stretch)

## Impacted components

- *frontend*

## Extra information

Edit: philipe 16/04 14:34

**Comment by PhilippeAccorsi** [comment] 2020-04-17 09:46
If you restart `install_frontend_dependencies.sh` (after pull some commit), All warning visible the first time, is not more visible. Strange.

**Comment by Skylsmoi** [comment] 2024-12-18 10:10
Can't reproduce.
Also, we now use yarn.
Closing

**Closed by Skylsmoi** 2024-12-18 10:10 UTC
Labels: frontend, to sort
