### ISSUE TITLE
Bug: Comments are sent with a span tag from autocomplete

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3581] opened 2020-09-14 15:30 UTC
## Description and expectations

The comments are send with a `<span id=autocomplete>`.

- [ ] Clean all comments before send.

_(Bug reported by @raphj )_

###

### Version information

- Tracim version: v3.1.0

________________________________________________

**Comment by raphj** [comment] 2020-09-18 07:17
Duplicate of #3548.

**Closed by raphj** 2020-09-18 07:17 UTC
Labels: frontend, mention autocomplete
