### ISSUE TITLE
Show webdav in dashboard when activated

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1335] opened 2019-01-17 14:33 UTC
Webdav feature ui has been desactivated since : https://github.com/tracim/tracim/issues/886
We should reenable it but let is appear only if a config parameter (`webdav.ui.activated` ?) is true.
Frontend will be able to find information in endpoint `/api/v2/system/config`

**Comment by PhilippeAccorsi** [comment] 2019-04-01 13:51
@inkhey @Skylsmoi this issue is to introduce link for webdav in dashbord (like we have in tracim_v1).

**Comment by PhilippeAccorsi** [comment] 2019-04-25 13:34
For this feature, after discuss with @inkhey and @lebouquetin we add one parameter in development.ini with value `True` by default. This parameter is used to inform frontend about webdav url.

If parameter is `True` => frontend show webdav url in dashbord of shared space
If parameter is `False` => frontend not show webdav url  in dashbord of shared space

**Comment by inkhey** [comment] 2019-04-26 09:13
@Skylsmoi @lebouquetin I need to transmit at least both webdav url and webdav activation boolean to frontend, i tried something in #1643, we need to validate parameter name (and config parameter name) an the way we transmit it (i prefer transferring only one complete url with protocol and let frontend convert to gnome protocol if needed ( https become davs and http become dav)).

**Comment by inkhey** [comment] 2019-04-30 13:50
current parameter are: 
- webdav_enabled as boolean False
- webdav_url as string like : https://localhost:3030/webdav
both returned by /api/v2/system/config

**Comment by lebouquetin** [comment] 2019-04-30 14:08
it's ok for me. I agree with one url only and the frontend build `davs://xxx` from `https://xxx`

**Comment by Skylsmoi** [comment] 2019-05-03 15:24
@PhilippeAccorsi Testing information:
I have removed the global css rule on link (tag <a>). This rule caused me too much trouble to overrides.
As a result, links all over Tracim might have a design regression.
I have check all Tracim and have already fixed most of them.
BUT, if you ever ends up, finding one or two, notify me and I'll do the necessary.
Theses missing links should looks like a default blue text instead of their usual color.

**Comment by PhilippeAccorsi** [comment] 2019-05-07 13:25
- [ ] Missing translate about webdav
- [ ] Missing translate about caldav
- [ ] Icon about url for webdav is not a good one (its the same like we have for calendar)
    - need to find/discuss about the good icon for this link
- [ ] text about agenda has change, but not in `My account > agenda`

**Comment by gbonaspetti** [comment] 2019-05-14 09:29
I solve the translation problems, including the fourth item, but it's still missing to solve the icon issue.

**Comment by gbonaspetti** [comment] 2019-05-14 10:10
Some ideas to the icon issue:
- we can use the Tracim symbol to link to what will be integrate (like we do in the agenda)
- we can choose something linked to integration, like fa-arrow-circle-o-right (https://fontawesome.com/v4.7.0/icon/arrow-circle-o-right)

**Comment by Skylsmoi** [comment] 2019-05-15 10:58
@gbonaspetti let's take the cloud https://fontawesome.com/v4.7.0/icons/

**Comment by PhilippeAccorsi** [comment] 2019-05-16 13:38
Verified.

**Closed by PhilippeAccorsi** 2019-05-16 13:38 UTC
Labels: frontend, verified
