### ISSUE TITLE
Clicking on a folder when a content is open doesn't close the content

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2128] opened 2019-07-30 13:18 UTC
## Bug description & symptom

When clicking on a folder (from workspace content list) while having a content opened, it changes the url and remove the part `:type/:contentId`.
Therefore, the content should close.

It is a regression, I tested with @PhilippeAccorsi on v2.1 and it worked.

## Diagnostic

This have to do with the changes in the frontend/dist/asset/tracim/appInterface.js

## Expected

The interface should stay synced with the url

## Context and version information

found in tracim v2.3.1+
not found in tracim v2.1

## How to reproduce

- Open a content
- click on a folder with the content still open
- the url changes but the content is still open

## Impacted components

frontend

**Comment by Quiwy** [comment] 2022-08-19 13:16
Can't reproduce on build_088, @Skylsmoi do you confirm we can close it?

**Comment by Skylsmoi** [comment] 2022-08-23 15:13
we can.
Furthermore, now we can't see the content list while a content is open so this issue cannot exists

**Closed** 2022-08-24 07:35 UTC
Labels: frontend, to sort
