### ISSUE TITLE
if image is added in html-document, this image is not visible in email but space of this image is used in email

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1830] opened 2019-05-31 13:59 UTC
## Bug description & symptom

One member add image in html-document, after that the other member receive an email notification but in this image we just see a big blanck space with file broken icon but image is not visible.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] show link (with url) for image
or
- [ ] show preview of image

## How to reproduce

- add an image in html-docment in one shared space with other member (this other member need to receive notification)

## Screenshots

![Capture d’écran de 2019-05-31 15-58-34](https://user-images.githubusercontent.com/25848257/58710666-2091e280-83bd-11e9-995f-80ae2616f56b.png)

## Impacted components
*"unknown"*

**Comment by tracim** [comment] 2019-06-03 08:27
This is not a bug. Here image is a link to mattermost but mattermost not authorized public access for image.

I close this issue.

**Closed by tracim** 2019-06-03 08:27 UTC
Labels: blocked by reporter, bug

**Comment by PhilippeAccorsi** [comment] 2019-06-03 08:39
This is not a bug. Here image is a link to mattermost but mattermost not authorized public access for image.

I close this issue.
