### ISSUE TITLE
Bug: Link previews of images output the binary code of the image as text

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4812] opened 2021-07-21 07:36 UTC
## Description and expectations

Link previews of images output the binary code of the image as text.

![image](https://user-images.githubusercontent.com/3817365/126448977-d70e0161-d4c6-4030-895c-4a194221e7fb.png)

### How to reproduce

1.Write a comment with this URL:  https://i.redd.it/buvti1j81dc71.jpg
2. Notice the binary soup! :plate_with_cutlery: 

### Version information

- Tracim version: v3.9, likely since the feature exists
- Web browser: any

## Diagnostic

The image is sent by the backend as-is in the description field of the json response of the endpoint `/url-preview` (see at the end for an example).

We should probably add a mime type field, base64-encode such previews, maybe use another field for such data (or not), and build previews with data urls in the frontend.

Output of an affected link preview:
```json
{"title": null, "image": null, "description": "\ufffd\ufffd\ufffd\ufffd JFIF      \ufffd\ufffdICC_PROFILE   lcms  mntrRGB XYZ \ufffd    ) 9acspAPPL                          \ufffd\ufffd     \ufffd-lcms                                               \ndesc   \ufffd   ^cprt  \\   wtpt  h   bkpt  |   rXYZ  \ufffd   gXYZ  \ufffd   bXYZ  \ufffd   rTRC  \ufffd   @gTRC  \ufffd   @bTRC  \ufffd   @desc       c2                                                                                  text    FB  XYZ       \ufffd\ufffd     \ufffd-XYZ         3  \ufffdXYZ       o\ufffd  8\ufffd  \ufffdXYZ       b\ufffd  \ufffd\ufffd  \ufffdXYZ       $\ufffd  \ufffd  \ufffd\ufffdcurv          \ufffd\ufffdc\ufffdk\ufffd?Q4!\ufffd)\ufffd2;\ufffdFQw]\ufffdkpz\ufffd\ufffd\ufffd|\ufffdi\ufffd}\ufffd\ufffd\ufffd0\ufffd\ufffd\ufffd\ufffd C \t\t\n\n\t\r\r\"##!  %*5-%'2(  .?/279<<C\n\n\n9& &99999999999999999999999999999999999999999999999999\ufffd\ufffd 9\ufffd \" \ufffd\ufffd             \ufffd\ufffd             \ufffd\ufffd     \ufffd\ufffd    s\ufffdi\ufffd\ufffdE,E=\ufffd                 \ufffd\u078f\ufffd\ufffd_\ufffd\ufffd\ufffd\ufffd[[\ufffd +\ufffd;cdts\ufffd                VE*\ufffd\ufffd\ufffd`\ufffd~\ufffdZ\ufffd\u0495\ufffdo\ufffd\ufffdM\ufffdcr(\ufffd8\ufffd\ufffd\ufffd                \ufffd\ufffd\ufffda\ufffd\ufffdj\"{\ufffd              \ufffdC\ufffd|\ufffdZ\ufffd}\ufffd$\ufffd\ufffd\ufffd\ufffd\u0291\ufffd/\u04d3\u05a0\ufffd\u0473~\ufffda\ufffd\ufffdq\"\ufffd\ufffdn\ufffd               \ufffdx|\ufffd\ufffd~\ufffd\ufffd\ufffd>\ufffd\ufffdJ\ufffd\ufffd\ufffd            ;G*\ufffd\ufffd\ufffd-_\ufffd\ufffd\ufffd\ufffdKT\ufffdg\ufffde\ufffdn\ufffd_i\ufffd\ufffd\ufffdOzY:\ufffdKV\ufffd\ufffdn\ufffd               1\ufffd\ufffd #\ufffd\ufffdc:\u013c\ufffdtb\ufffd^\ufffd \ufffd;\ufffdy\ufffdm\u03fe\ufffdj\ufffd\ufffdn\ufffd\ufffd=\ufffd[\ufffd\ufffd\u007f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd w\ufffdt            \ufffd\ufffd\ufffd4`\u03d5>\ufffdG\ufffd\ufffd\ufffd\ueb6asu\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdR\ufffdn\ufffdZY\ufffd@               \ufffd_\ufffdQ\ufffd>f?\ufffd\ufffd=\ufffdr-\ufffdx\ufffd\ufffd\ufffd]\ufffdfz\ufffd\ufffd=\ufffd\ufffd\ufffdt\ufffd\ufffd8-\ufffd\ufffd~\ufffdA\ufffd>\ufffdO\ufffd\ufffdMp\ufffdi@            g\ufffd\ufffd\ufffdg\ufffd\ufffd\ufffd\ufffd\u0296\ufffd}\ufffdR\ufffdm\ufffdif\ufffd               \ufffd\ufffd9\ufffd\ufffd\ufffdkyF\ufffd\ufffd\ufffd\ufffd,\ufffdUf.\ufffd^\ufffd\ufffd\ufffd$\ufffdIU\ufffdidLV\ufffdq\ufffd\ufffd|\ufffd\ufffdg\ufffd\ufffd\u032d\ufffd~Y\ufffd\uad5e\ufffd\t          s\ufffd  C2\"\ufffd\ufffd\ufffd\ufffd\u0450[tR\ufffdR\ufffd\ufffd\ufffd              xz\ufffdS-~\ufffd\ufffd_\ufffd+\ufffd[\ufffd\ufffdy\ufffdK\ufffd\u04e3c\ufffd\r\ufffdq'5)\\\u0365\ufffd\ufffd\ufffde\ufffd\ufffd\ufffdG>\ufffd9t$\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdx\ufffd\ufffd k\ufffd\ufffd\ufffd          \ufffd{$k|\uec5d"}
```

**Comment by inkhey** [comment] 2022-02-22 14:42
The problem is due to the webpreview lib that doesn't check for html content type for unclear reason beautifulsoup success to parse a binary content image to get a description for the "GenericPreview". This problem should be fixed by https://github.com/tracim/tracim/issues/4439 as we will handle non-html-file separately from others which mean no parsing of non-html file.

**Comment by gbonaspetti** [comment] 2022-05-27 08:19
Fixed https://github.com/tracim/tracim/pull/5439

**Closed by gbonaspetti** 2022-05-27 08:19 UTC
Labels: frontend, backend, preview(link)
