### ISSUE TITLE
Bug: The invalid mention popup displays with a valid mention

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4006] opened 2021-01-04 16:31 UTC
## Description and expectations

When mentioning a user in a comment it can happen that the "invalid mention" popup appears when sending the comment. The problem disappears when reloading the tab and sending the previously copied comment.

### How to reproduce

**RANDOM**

1. Add a comment with a mention
2. Click on send

### Version information

- Tracim version: 3.4.1
- Web browser: Firefox

## Screenshots

________________________________________________

## Diagnostic

As the problem is solved when reloading the tab, the cause could be a bad members list.

**Comment by gbonaspetti** [comment] 2021-07-28 10:25
Closing because it's a duplicate of #4666

**Closed by gbonaspetti** 2021-07-28 10:25 UTC
Labels: to sort
