### ISSUE TITLE
Bug: Caldavzap doesn't properly handle a description created by Thunderbird 91.5

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5430] opened 2022-02-15 11:04 UTC
~~PR: #5463~~ 
PR: #5469

## Description and expectations

Thunderbird 91.5 creates description for events in a way caldazap doesn't handle which leads to 2 issues:
- Event description from thunderbird are not read by caldavzap
- Caldavzap can't edit description if thunderbird has already created a description as when it apply the change, it tries to add 2 descriptions which is invalid.

### How to reproduce

1. Go to tracim web calendar  
2. Add event and edit a description
3. Go to thunderbird 
4. Edit the description of the existing event
5. Refresh tracim web calendar
6. Check description and try to edit it.

### Version information

- Tracim version: 4.1.1
-  Thunderbird: 91.5

## Diagnostic

get Event/description created from caldavzap:

```
REPORT http://localhost:7999/dav/agenda/workspace/1/
<?xml version='1.0' encoding='utf-8'?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><response><href>/dav/agenda/workspace/1/8ef7a3663d0cd79dff9c3e91be1119d193fc02fd57fd383b67cebb23f32d737b.ics</href><propstat><prop><getcontenttype>text/calendar;charset=utf-8;component=VEVENT</getcontenttype><getetag>"f71740e041c58c0d5701f50fa66577f5"</getetag><C:calendar-data>BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//Inf-IT//CalDavZAP 0.13.1//EN
BEGIN:VEVENT
UID:al9h7ry7-ffmb-04q0-xmha-gjq5k1m0vh4p
DTSTART;VALUE=DATE:20220216
DTEND;VALUE=DATE:20220217
CLASS:PUBLIC
CREATED:20220215T104424Z
DESCRIPTION:test
DTSTAMP:20220215T104424Z
LAST-MODIFIED:20220215T104424Z
SUMMARY:Super !
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
</C:calendar-data></prop><status>HTTP/1.1 200 OK</status></propstat></response></multistatus>
```

Event/description modified by thunderbird:

```
REPORT http://localhost:7999/dav/agenda/workspace/1/
<?xml version='1.0' encoding='utf-8'?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><response><href>/dav/agenda/workspace/1/8ef7a3663d0cd79dff9c3e91be1119d193fc02fd57fd383b67cebb23f32d737b.ics</href><propstat><prop><getcontenttype>text/calendar;charset=utf-8;component=VEVENT</getcontenttype><getetag>"47d7139dab21f26fff92f1cf15f14ede"</getetag><C:calendar-data>BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
BEGIN:VEVENT
UID:al9h7ry7-ffmb-04q0-xmha-gjq5k1m0vh4p
DTSTART;VALUE=DATE:20220216
DTEND;VALUE=DATE:20220217
CLASS:PUBLIC
CREATED:20220215T104424Z
DESCRIPTION;ALTREP="data:text/html,%3Cbody%3Etest%20(updated%20by%20thunder
 bird)%3C%2Fbody%3E":test (updated by thunderbird)
DTSTAMP:20220215T104807Z
LAST-MODIFIED:20220215T104807Z
SUMMARY:Super !
TRANSP:OPAQUE
X-MOZ-GENERATION:1
END:VEVENT
END:VCALENDAR
</C:calendar-data></prop><status>HTTP/1.1 200 OK</status></propstat></response></multistatus>
```

Failed PUT request on description already edited with thunderbird:
```
PUT http://localhost:7999/dav/agenda/workspace/1/8ef7a3663d0cd79dff9c3e91be1119d193fc02fd57fd383b67cebb23f32d737b.ics
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20220215T104424Z
LAST-MODIFIED:20220215T105000Z
DTSTAMP:20220215T105000Z
UID:al9h7ry7-ffmb-04q0-xmha-gjq5k1m0vh4p
SUMMARY:Super !
TRANSP:OPAQUE
DESCRIPTION:qdsqsd
CLASS:PUBLIC
DTSTART;VALUE=DATE:20220216
DTEND;VALUE=DATE:20220217
DESCRIPTION;ALTREP="data:text/html,%3Cbody%3Etest%20(updated%20by%20thunder
 bird)%3C%2Fbody%3E":test (updated by thunderbird)
X-MOZ-GENERATION:1
END:VEVENT
PRODID:-//Inf-IT//CalDavZAP 0.13.1//EN
END:VCALENDAR

```
There is nothing specific in response (400 code and "Bad request" text).

Error from console log when caldavzap tried to update description created from thunderbird:

```
022-02-15 10:43:48 WARNI [radicale:950][waitress-3] Bad PUT request on '/agenda/workspace/1/a3e33f6d4ea234b8b767ee6b99fd05bf8228bfc3633b23ddda18f2dc945a8c25.ics/': Failed to store item 'a3e33f6d4ea234b8b767ee6b99fd05bf8228bfc3633b23ddda18f2dc945a8c25.ics' in collection 'agenda/workspace/1': 'VEVENT components cannot contain more than 1 DESCRIPTION'
Traceback (most recent call last):
  File [...]/lib/python3.9/site-packages/radicale/storage.py", line 1484, in upload
    self._store_item_cache(href, vobject_item)
  File "[...]/lib/python3.9/site-packages/radicale/storage.py", line 1304, in _store_item_cache
    content = self._item_cache_content(vobject_item, cache_hash)
  File "[...]/lib/python3.9/site-packages/radicale/storage.py", line 1292, in _item_cache_content
    text = vobject_item.serialize()
  File "[...]/lib/python3.9/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "[...]/lib/python3.9/site-packages/vobject/icalendar.py", line 1001, in serialize
    cls.validate(obj, raiseException=True)
  File "[...]/lib/python3.9/site-packages/vobject/behavior.py", line 85, in validate
    if not child.validate(raiseException, complainUnrecognized):
  File "[...]/lib/python3.9/site-packages/vobject/base.py", line 124, in validate
    return self.behavior.validate(self, *args, **kwds)
  File "[...]/lib/python3.9/site-packages/vobject/icalendar.py", line 1170, in validate
    return super(VEvent, cls).validate(obj, raiseException, *args)
  File "[...]/lib/python3.9/site-packages/vobject/behavior.py", line 98, in validate
    raise base.ValidateError(m.format(cls.name, val[1], key))
vobject.base.ValidateError: 'VEVENT components cannot contain more than 1 DESCRIPTION'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[...]/lib/python3.9/site-packages/radicale/__init__.py", line 948, in do_PUT
    new_item = parent_item.upload(href, items[0])
  File "[...]/lib/python3.9/site-packages/radicale/storage.py", line 1486, in upload
    raise ValueError("Failed to store item %r in collection %r: %s" %
ValueError: Failed to store item 'a3e33f6d4ea234b8b767ee6b99fd05bf8228bfc3633b23ddda18f2dc945a8c25.ics' in collection 'agenda/workspace/1': 'VEVENT components cannot contain more than 1 DESCRIPTION'
2022-02-15 10:43:48 INFO  [radicale:384][waitress-3] PUT response status for '/agenda
```

Caldavzap doesn't detect the `DESCRIPTION` field of thunderbird as a description (its detection is based on a regex, so probably the regex is not adapted). The correct behavior should be to detect properly then overwrite the description entirely if it is modified (see https://bugzilla.mozilla.org/show_bug.cgi?id=1748002 and https://github.com/nextcloud/calendar/issues/3863).

**Comment by grignards** [comment] 2022-02-23 10:55
@knodelle caldavzap's code is in `frontend/dist/assets/_caldavzap/`.

**Comment by gbonaspetti** [comment] 2022-02-28 14:24
Tested on branch

**Comment by sicherist** [comment] 2022-02-28 22:31
Thank you for working on this! This issue becomes a little more confusing. After applying your patch, caldavzap can display and edit descriptions created in Thunderbird.
But after I made changes in caldavzap to an event that was created in Thunderbird - then the changes made my caldavzap are not visible in Thunderbird. To me it looks like Caldavzap will only add to the DESCRIPTION after the colon but leave the ALTREP untouched so they will be inconsistent. An example:
DESCRIPTION;ALTREP="data:text/html,%3Cbody%3ETEST%20created%20in%20TB%3C%2F body%3E":TEST created in TB\nmodified by caldavzap

Thunderbird will only display the ALTREP description and will overwrite both if I make an edit in Thunderbird.

By the way - even weirder: When mouse-hovering on a task in thunderbird, then the mouse-over-preview will display the non-altrep-description, while opnening the task will display the ALTREP-descripton: [https://up.picr.de/43115454dt.jpg](url) (could someone show this screenshot in the bugzilla-thread? I no longer have a bugzilla-account)

Thunderbird intruduced quite a confusion with their adoption of the ALTREP-thing - even if it is part of the caldav-spec.

I think the best way to handle this would be, if caldavzap would either edit both the normal description and the ALTREP-description. Or to remove the ALTREP-descripton when a change is made to the description.

**Comment by knodelle** [comment] 2022-03-01 10:32
Thank you for your comment @sicherist. 
We weren't able to reproduce.

Are you using Tracim's caldav? If yes, what Thunderbird version are you using? 
For your information, our fix only applies to events, not tasks.

**Comment by gbonaspetti** [comment] 2022-03-01 12:49
Done

**Closed by gbonaspetti** 2022-03-01 12:49 UTC
Labels: manually tested, frontend, app-agenda, add to changelog

**Comment by lebouquetin** [comment] 2022-03-01 13:21
@gbonaspetti @knodelle I'd like to test somewhere with my environment. Is there a running dev env somewhere?

**Comment by lebouquetin** [comment] 2022-03-01 13:29
@inkhey can you test please with your environment?
