### ISSUE TITLE
sharp (#) at the end of the calendar url broke radicale file structure

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#53] opened 2016-06-20 08:32 UTC
See server log (tested with "Intranet")

**Comment by tracim** [comment] 2016-06-20 08:41
Renamed as the issue is due to the "user-friendly" calendar url. Need to remove the user friendly part (#intranet in the example)

**Comment by tracim** [comment] 2017-06-23 13:27
Is it fixed or not ?

**Comment by algooapy** [comment] 2017-08-07 09:16
- Issue not reproduced.
- Seems to have been fixed by buxx@68b7c40 in:
`tracim/tracim/model/data.py:Workspace.calendar_url`

**Closed by algooapy** 2017-08-07 09:16 UTC
