### ISSUE TITLE
Content: Add a "print document" feature

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1355] opened 2019-01-23 21:29 UTC
Text documents are not ready to print. It would be nice to have a "print" button showing the document ready-to-print. The top would be to be able to use a customisable template.

What about using https://weasyprint.org/ ?

**Comment by metzgegu** [comment] 2020-02-20 13:03
duplicate of #268, but we will keep ideas from this ticket

**Closed** 2020-02-20 13:05 UTC
Labels: enhancement, to sort
