### ISSUE TITLE
Bug: Switching between two contents of the same type in different workspaces does not work

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3578] opened 2020-09-14 15:17 UTC
## Description and expectations

If you click on a notification from a different space than the one you are in and both contents have the same type, the app doesn't open.

### How to reproduce

1. From admin account, create a user
2. Create public spaces s1 and s2 (or confidential spaces to which this user has access)
3. Create notes / HTML documents t1 and t2
4. log as the user
5. open t1
6. click on the notification to open t2

### Diagnostic

`OpenContentApp`, which handles app switching, has a bug in its state handling.

When going to another content in another workspace but which has the same type as the content currently opened, the app is closed. Then, when OpenContentApp is supposed to re-open the app on the other workspace, it "thinks" the app is still open, so it simply requests the app to load the new content. But since the app is actually closed, it could not fulfill the request.

### Version information

- Tracim version: v3.4
- Web browser: Firefox

**Comment by raphj** [comment] 2020-09-16 08:32
probably related to #3518

**Comment by raphj** [comment] 2020-09-16 12:24
@gbonaspetti still sees the issue with #3595

**Comment by raphj** [comment] 2020-09-18 08:00
We are testing this on preprod in the hope that #3595 fixed this.

**Comment by PhilippeAccorsi** [comment] 2020-09-18 13:56
Need a quick test when all fix for 3.1.1 are merged in maintenance/3.1 (just to make sure this bug no more exists).

**Comment by PhilippeAccorsi** [comment] 2020-09-21 09:38
Not working on preprod. No error visible in network or console. All seems working good but app is not openned, like if app is invisible.

**Comment by PhilippeAccorsi** [comment] 2020-09-21 09:38
I think its a fix for 3.1.2

**Comment by PhilippeAccorsi** [comment] 2020-09-21 09:45
![bug_app_wall](https://user-images.githubusercontent.com/25848257/93753090-e24ab300-fbff-11ea-8006-3b6318d260fb.gif)

**Comment by lebouquetin** [comment] 2020-10-29 16:04
I do not understand the relationship with custom event. For me - this is something we talked about, the behavior should be:

1. a click change the url
2. on url change, the frontend update the view

There should not be two processes (one updating the url and one changing the view) because this is impossible to keep things always synchronized...

Maybe I do not understand the bug; if so, tell me.

**Comment by raphj** [comment] 2020-10-29 17:01
(after discussion)

The bug is probably in the generic mechanism handling routes rather than because the mechanism is not generic, but we need to look into this to be sure.

**Comment by raphj** [comment] 2021-01-06 09:21
We managed to reproduce this bug reliably. I added steps to reproduce.

**Comment by raphj** [comment] 2021-01-15 07:58
:warning: App switching has been reworked quite a bit. 

Test instructions: https://github.com/tracim/tracim/pull/4022#issuecomment-760719667

**Comment by Skylsmoi** [comment] 2021-01-15 13:44
I have found a case where the app feature isn't close when it should:
- open a space
- open a content
- open another content in the same space
- click on the activity feed
- the content stays open
Note that you can only reproduce it by opening at least 2 contents in the same space. If you only open one, click on the activity feed properly closes the content

**Comment by raphj** [comment] 2021-01-15 15:22
Good catch. I am going to fix this.
For the record, this is not a regression of this fix, this bug is in a released version of Tracim.

**Comment by Skylsmoi** [comment] 2021-01-18 10:32
tested on branch
since the spotted issue isn't a regression, a specific issue will be created for it

**Comment by raphj** [comment] 2021-01-18 10:44
This issue lives here: https://github.com/tracim/tracim/issues/4060

**Comment by PhilippeAccorsi** [comment] 2021-01-22 09:33
Done

**Closed by PhilippeAccorsi** 2021-01-22 09:33 UTC
Labels: add to changelog, frontend, manually tested
