### ISSUE TITLE
Bug: elapse time visible in notification wall is not the good one after upgrade tracim from 3.8.2 to 4.0.3

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5152] opened 2021-12-10 00:51 UTC
## Description and expectations

I have update an Tracim instance from 3.8.2 to 4.0.3 and after this upgrade I can seen wrong time in notification wall.

The lmouseover show a good date and time and if I use devtool I can seen this:

![Capture d’écran du 2021-12-10 01-44-03](https://user-images.githubusercontent.com/25848257/145498354-b000c8ac-e5ca-4e1a-98b9-6e8e9637d825.png)

We can seen in the screen shot date and time `07/10/2021, 18:03:15` but information of time elapse `3 m`.

### How to reproduce

I think it is just necessary to upgrade tracim.

### Version information

- Tracim version: 4.0.3
- Web browser: Firefox
- Version: 94.0
- Device / System: Ubuntu 20.04

### Screenshots

________________________________________________

**Comment by Skylsmoi** [comment] 2021-12-10 11:50
3m actually means "3 months" not "3 minutes"

So, not a bug.

As seen with Philippe, I'm closing the issue

**Closed by Skylsmoi** 2021-12-10 11:50 UTC
Labels: frontend, to sort, ux
