### ISSUE TITLE
Bug: links to comments from mail notifications are either wrong or not handled

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5160] opened 2021-12-14 08:07 UTC
## Description and expectations

When one edits a comment in a publication, the mail notification contains a link to a comment, instead of a thread. The frontend displays the space's list of contents, instead of opening the thread at the place of the comment.

I expect one of these two things:
- the thread app should be opened, scrolled to the comment (ideally)
- the email notification should use a link to the content and not the the comment 

### How to reproduce

1. Be in the same space as A, in which you have enabled email notifications
2. make A write a comment in a publication
3. make A edit their comment

Links look like: https://instance.example/ui/workspaces/162/contents/comment/45047

### Version information

- Tracim version: 4.0
- Web browser: any

## Diagnostic

Links to comments are not implemented in the frontend

**Comment by Quiwy** [comment] 2022-08-23 08:12
Related to #5000 and #2630, just tested, still existent in build_088.

Duplicate of #1691 so closing it.

**Closed by Quiwy** 2022-08-23 08:12 UTC
Labels: frontend, to sort, email, app-thread
