### ISSUE TITLE
Bug: responsive: frontend show some information behind sidebar but width is not too small to show all content near the sidebar (on desktop machine)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4199] opened 2021-02-19 09:42 UTC
## Description and expectations

In some tracim view, when the width is less than 1209px, some information is show behind the sidebar, but is not necessary at this time because tracim can show content on smaller screen correctly (this is visible if you close sidebar and continue to reduce width).
So I think we need to reduce the size of what is shown when sidebar is openned and show information behind sidebar just on a very small screen (like we show on smartphone).

### How to reproduce

- open list of content
- reduce width of screen

### Version information

- Tracim version: 3.5.0 (and I think oldest version)
- Web browser: Firefox
- Version: 78.7.0esr
- Device / System: Buster

## Screenshots

https://user-images.githubusercontent.com/25848257/108487092-24efe480-729f-11eb-9d29-8425bc16ba7b.mp4

________________________________________________

**Comment by Skylsmoi** [comment] 2024-07-04 13:33
With the new design, the sidebar, in mobile and small screen, is either full width of closed.
We can't reproduce this issue.
Closing it

**Closed by Skylsmoi** 2024-07-04 13:33 UTC
Labels: frontend, to sort, ux, responsive
