### ISSUE TITLE
admin_user: deactivate possibility for admin to deactivate is own account

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#992] opened 2018-10-05 14:43 UTC
at present

admin can deactivate is own account

Expected

its not possible for admin to deactivate is own account.
its also impossible to deactivate all other function of is own account because after that nobody can admin again.

(@lebouquetin maybe its possible if tracim have an another admin?)

**Comment by PhilippeAccorsi** [comment] 2018-10-09 13:08
Verified.

**Comment by lebouquetin** [comment] 2018-10-12 16:45
I reopen this issue because it MUST be implemented in backend

**Comment by tracim** [comment] 2018-11-21 20:17
duplicate of https://github.com/tracim/tracim/issues/1014 . this is fixed

**Closed by tracim** 2018-11-21 20:17 UTC
Labels: Highest priority, backend, bug
