### ISSUE TITLE
Bug: Duplicate member in the dashboard member list

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3784] opened 2020-11-03 07:56 UTC
![image](https://user-images.githubusercontent.com/3817365/97960787-5dcc8200-1db2-11eb-82c7-fb5f6bd96b16.png)

# Diagnostic

Idea: a duplicated key in this React component?

**Comment by Skylsmoi** [comment] 2024-06-24 10:12
no information in the issue, can't reproduce and never has been seen

closing the issue

**Closed by Skylsmoi** 2024-06-24 10:12 UTC
Labels: frontend
