### ISSUE TITLE
Bug: when I call someone on tracim, sometimes two windows open 

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5337] opened 2022-02-01 16:30 UTC
### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

**Comment by Relf-Algoo** [comment] 2022-05-06 07:50
@PhilippeAccorsi Do you know if this still exists ?

**Comment by PhilippeAccorsi** [comment] 2022-05-10 08:15
I don't know.

**Comment by Skylsmoi** [comment] 2024-08-28 12:00
could not reproduce, might be fixed by https://github.com/tracim/tracim/pull/6529

**Closed** 2024-09-25 08:09 UTC
Labels: to sort, requested
