### ISSUE TITLE
delete button on app gallery is visible also for reader role

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2648] opened 2020-01-29 09:39 UTC
## Bug description & symptom

In app gallery, delete button is visible for all member role. In other app, delete button is just visible
for member with role Content manager and manager. This is just a visual bug because user without role Content manager or manager can't delete file. 

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [x] delete button is just visible if you have role `Content manager` or `Manager`

## How to reproduce

- open gallery

## Impacted components

- *frontend*

**Comment by metzgegu** [comment] 2020-03-05 10:22
This issue was caused by an other issue in frontend, but it was fixed in #2608

**Comment by PhilippeAccorsi** [comment] 2020-03-18 10:37
Verified. (Wait merge to close)

**Closed** 2020-03-18 18:07 UTC
Labels: Gallery, UX, frontend, verified
