### ISSUE TITLE
Feat: Display child spaces and their access types in the sidebar

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3579] opened 2020-09-14 15:25 UTC
## Feature description and goals

Child spaces (see #3546) must be displayed in the sidebar as a tree:

![sidebar](https://user-images.githubusercontent.com/35422692/94559597-c54a5b80-0261-11eb-9793-21be0e0d6267.png)

- [x] All spaces the user is member of shall be displayed in the sidebar
- [x] All tree items are always unfolded (so that all child spaces are visible)
- [x] Scrollbar handling stays the same as currently
- [x] Clicking on a space item shall open the space's dashboard
- [x] The current space shall be displayed in bold+underline:

![highlight](https://user-images.githubusercontent.com/35422692/94573017-f6328c80-0271-11eb-9bb8-4519d396eb09.png)

- [x] It is possible for a user to have access to a sub-space without having access to its parent. In this case the sub-space shall be treated as a root space for displaying it.
- [x] The "drag-and-drop" icon that was displayed when we moved some content will be displayed at the left corner, this will "move" the space's title, but it's an acceptable temporary solution until we think in a better way of show it.

## Prerequisites

- #3546 (merged)
- https://github.com/tracim/tracim/issues/3584 (merged)

### Finalize the access type icons

_2020-09-29_ **Decision**: We are not going to display the type icons in the sidebar.

### Should the tree structure be built by the frontend or by the backend?

Building the tree structure in the frontend is possible (since the API will provide a `parent_id` filter), but less efficient than a backend approach (the frontend will need *n*+1 queries where *n* is the number of spaces the user is member of).
A backend approach is more efficient (a single SQL query could do the job) but is more "specialized".
The code complexity should be similar for both solutions.

**Decision**: A last approach (and the one we chose) is for the backend to return all spaces a user has access to (with the `parent_id` information in them), then the frontend builds its tree from this list.

**Comment by raphj** [comment] 2020-09-15 09:30
> the frontend will need n+1 queries
What to you mean? It will need to fetch data about each space via HTTP?

Then I'm for the creation of an endpoint that gives the tree with all the needed data so the frontend can fetch all the data in one request.

But can't the backend just send the list of the spaces of which the user is member, with their parent id, in one go, with the existing endpoint? If so, I think building the tree should be done by the frontend, because showing them as a tree is a UI decision.

**Comment by inkhey** [comment] 2020-09-15 09:39
> > the frontend will need n+1 queries
> 
> What to you mean? It will need to fetch data about each space via HTTP?
> 
> Then I'm for the creation of an endpoint that gives the tree with all the needed data so the frontend can fetch all the data in one request.
> 
> But can't the backend just send the list of the spaces of which the user is member, with their parent id, in one go, with the existing endpoint? If so, I think building the tree should be done by the frontend, because showing them as a tree is a UI decision.

Depending on how costly is it, backend is able to do recursive query to get the information we need, but it's not trivial.

**Comment by inkhey** [comment] 2020-09-15 09:43
> But can't the backend just send the list of the spaces of which the user is member, with their parent id, in one go, with the existing endpoint? If so, I think building the tree should be done by the frontend, because showing them as a tree is a UI decision.

Don't see any reason to not provide the parent_id in the current endpoint. so, yes.

**Comment by lebouquetin** [comment] 2020-09-15 09:45
@grignards @inkhey @raphj:

- we already have a endpoint returning the list of user spaces
- the  frontend will have information allowing to rebuild the treeview
- by the way, it will allow to get subspaces which are accessible but parents are not (and in this case, the correct behavior is to put them at the end of the list, like "root" spaces

**Comment by grignards** [comment] 2020-09-15 09:46
> But can't the backend just send the list of the spaces of which the user is member, with their parent id, in one go, with the existing endpoint? If so, I think building the tree should be done by the frontend, because showing them as a tree is a UI decision.

Yes this is also possible.

**Comment by lebouquetin** [comment] 2020-09-15 09:53
an important point is that the processing may result in spaces without parent available. These spaces must be append at the end of the treeview. This will make tracim more resilient in wrong usage of spaces / subspaces

**Comment by gbonaspetti** [comment] 2020-10-01 07:03
even this issue is still blocked by backend (3546), I pass the issue to `In progress` because I could start some interface updates in the branch `feat/3579__update_sidebar`

**Comment by inkhey** [comment] 2020-10-09 07:18
Just one clarification point about tree hierarchy and right access, as explained here:
>  It is possible for a user to have access to a sub-space without having access to its parent. In this case the sub-space shall be treated as a root space for displaying it.

This mean for this hierarchy or workspace:
```
.
└── Parent A
    ├── Children B
    └── Children C
        └── Grandson D
```
User A which as access to both A and D, should get:
```
.
├── Parent A
└── Grandson D
```

Another "logical" solution may be:
```
.
└── Parent A
    └── Grandson D
```
but such solution complexify the mecanism at lot, so it's not the solution choosen.

This hierarchy issue is not only frontend related, the same hierarchy should be handled for Webdav in backend, see https://github.com/tracim/tracim/issues/3549

**Comment by PhilippeAccorsi** [comment] 2020-10-14 15:48
For test on branch:
~~~
Finalize the access type icons
2020-09-29 Decision: We are not going to display the type icons in the sidebar.
~~~
- regression with button to close sidebar, after quick investiguate with @Skylsmoi we have find problem here: regression introduce when fix this issue https://github.com/tracim/tracim/pull/3638 and its here https://github.com/tracim/tracim/pull/3638/files#diff-80dab3c2de1deb73c7232c2f71514a8753dd649dcaa60c0a8ad75d212fb3ef67L40 (move `overflow hidden` create this regression)

More test tomorrow.

**Comment by PhilippeAccorsi** [comment] 2020-10-15 08:24
> For test on branch:
> 
> ```
> Finalize the access type icons
> 2020-09-29 Decision: We are not going to display the type icons in the sidebar.
> ```
> 
>     * regression with button to close sidebar, after quick investiguate with @Skylsmoi we have find problem here: regression introduce when fix this issue #3638 and its here https://github.com/tracim/tracim/pull/3638/files#diff-80dab3c2de1deb73c7232c2f71514a8753dd649dcaa60c0a8ad75d212fb3ef67L40 (move `overflow hidden` create this regression)
> 
> 
> ![click_not_work](https://user-images.githubusercontent.com/25848257/96013531-a9d87680-0e45-11eb-8cc7-0b3fe8b8ee3b.gif)
> 
> More test tomorrow.

Regression issue available in v3 backlog => https://github.com/tracim/tracim/issues/3693

**Comment by PhilippeAccorsi** [comment] 2020-10-15 08:24
Scroll on sidebar issue available in v3 backlog => https://github.com/tracim/tracim/issues/3694

**Comment by PhilippeAccorsi** [comment] 2020-10-15 08:25
Wait merge to close this issue.

**Comment by PhilippeAccorsi** [comment] 2020-10-15 08:40
Done.

**Closed by PhilippeAccorsi** 2020-10-15 08:40 UTC
Labels: add to changelog, frontend, manually tested, ux
