### ISSUE TITLE
Feat: Add a filter to the notification wall

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5590] opened 2022-04-12 09:35 UTC
## Feature description and goals

The user should be able to filter the notification on their wall, in order to manage them more easily, especially when the notifications ar too numerous.

**Comment by Quiwy** [comment] 2022-06-29 07:13
I agree, at least we should be able to filter read vs unread notifications in order to find "old" unread notifications

**Comment by grignards** [comment] 2022-09-01 13:36
Related to: https://github.com/tracim/tracim/issues/3324, maybe event duplicate?

**Comment by Haskaris** [comment] 2022-10-18 09:35
Closing since duplicate of #3324

**Closed by Haskaris** 2022-10-18 09:35 UTC
Labels: to sort
