### ISSUE TITLE
Creation of new content is broken in workspace if one content doesnt exist anymore in filedepot

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2605] opened 2020-01-06 14:43 UTC
## Bug description & symptom

In some very specific case when depot is dropped but not database, it's not possible anymore to create depot file (which is maybe normal ?) but error is about "uuid already exist" (uuid of file is created by filedepot).

## Expected

unclear

**Comment by PhilippeAccorsi** [comment] 2020-01-06 16:07
In this case to solved problem you need:
- create backup of your db (if necessary)
- delete your db with tracimcli db delete --force
- create new db with tracimcli db init

After that you can use again tracim.

**Comment by inkhey** [comment] 2020-01-14 15:06
Problem is not related to uniqueness but to check of workspace size which mean process will check all existing content size before add a new one, if old content are broken, creation endpoint failed dues to broken content.

**Comment by Skylsmoi** [comment] 2024-12-18 11:21
can't reproduce
closing

**Closed by Skylsmoi** 2024-12-18 11:21 UTC
Labels: backend, to sort, draft
