### ISSUE TITLE
Bug: Tracim's header can disappear on mobile

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#5117] opened 2021-11-24 09:39 UTC
## Description and expectations

Sometimes, the Tracim's header disappears on mobile and there is no way to make it visible again until you fully reload the page.

### How to reproduce

I currently don't have a way to reproduce it 100%. What's mostly work is:
- Open Tracim on a mobile
- Open a space's dashboard
- Refresh page
- Open sidebar
- Open notification wall
- Click on some content

### Version information

- Tracim version: v4.0.2
- Web browser: reproduced on
  - android safari
  - android chrome
  - iphone safari
- Version: latest
- Device / System: Android 10 / iOS 14

### Screenshots

________________________________________________

## Diagnostic

It appears the bug isn't reproducible neither on PWA nor on desktop browser using responsive dev tool.

Though it is reproducible on Android simulator using Chrome. Api version 29 (android 10).

When the issue occurs, using remote debug chromium dev tools, we can see the header is present on the page but ends up above the screen and isn't scrollable to.

Maybe linked to https://dev.to/rachelg/a-javascript-fix-for-the-100vh-problem-on-mobile-screens-9im#:~:text=not%20always...-,100vh.,of%20rems%20of%20your%20design. (needs investigation)

## Prerequisites

PR:
- #5122
- #5158

**Comment by Skylsmoi** [comment] 2021-11-24 10:02
It appears it is only reproducible when the device adds an address bar.
This would explain the non reproducibility on PWA and desktrop

**Comment by Skylsmoi** [comment] 2021-11-24 10:36
It seems the issue only occurs when opening a content.

I couldn't manage to reproduce it by opening anything other than a content.
This could means the issue comes from the apps or from the space content list page.

But opening popup create content apps doesn't seem to reproduce the issue. So the issue might not be in space content list page

**Comment by Skylsmoi** [comment] 2021-11-24 10:43
I confirm that I can only reproduce the issue when opening a content from a redirection OR a first page load.

This means that, if I open and close contents, open advanced dashboard app, open create content app, open create space app ... without ever doing a redirection at the same time, the issue doesn't occur.
So the issue only happens when loading the content list at the same time of opening the app (don't know if it is related, it's just the use case to reproduce the issue).

**Comment by Skylsmoi** [comment] 2021-11-24 13:12
Summary
To reproduce:
- Use tracim on a mobile
  - don't use PWA
  - don't use desktop browser responsive dev tools
- Open content from space dashboard recent activities
  - Don't open a news in recent activities
  - Don't open "open as content" from the page News
- Alternatively, first page load on a content route
- Keep in mind that it's not reproducible at 100%

**Comment by Skylsmoi** [comment] 2021-11-24 13:33
debug test:
- The bug happens even if app doesn't open (import script commented)
- It happens if I comment <OpenContentApp /> in WorkspaceContent.jsx
- It stopped happening after commenting `if (shouldScrollToContent) this.scrollToActiveContent()` inside `loadAllWorkspaceContent`

So it is the generated scroll that is causing the issue \o/

**Comment by Skylsmoi** [comment] 2021-11-24 14:11
related solution details: https://stackoverflow.com/questions/11039885/scrollintoview-causing-the-whole-page-to-move/11041376

**Comment by Skylsmoi** [comment] 2021-11-24 14:11
solution is to switch from `.scrollIntoView()` to `domElementToScrollTo.parentNode.scrollTop = domElementToScrollTo.offsetTop`

**Comment by MariePrandstetter** [comment] 2021-11-25 13:04
tested on branch

**Comment by Skylsmoi** [comment] 2021-11-29 08:57
issue doesn't seem to be fully resolved.
Quickest way to fix it would be to remove entirely the scroll on mobile by using the `isMobile` feature.
More research are required to understand why the issue persists though

**Comment by Haskaris** [comment] 2021-12-13 15:39
As discussed with @Skylsmoi we have chosen to remove the scroll on smartphones. This is ~~an ugly~~ a quick solution that require some discussion about, that's why the PR #5158 is still on draft.

Even if we found a reliable way to reproduce the bug, it looks like it depends of the loading duration of the page. On Algoo's preprod instance, I can manage to reproduce the bug, while I  can't reproduce it locally.

**Comment by knodelle** [comment] 2021-12-20 13:35
tested on branch

**Comment by Haskaris** [comment] 2021-12-22 15:02
During test period, we found some other way to hide the header:
- Use the smartphone previous button from `account settings`
- Select a text field - like you are going to edit it - move it away (out of the screen), then edit it

**Comment by gbonaspetti** [comment] 2022-01-10 08:26
Clicking on the notifications makes the header disappear on IOs

**Comment by PhilippeAccorsi** [comment] 2022-03-09 11:01
I have the same problem with opera. I have open tracim from email link, but also If I refresh the page, the header is never accessible. I can seen 1-2px of the header but I can use that. So it is impossible to disconnect from example.

**Comment by Haskaris** [comment] 2022-04-19 08:02
> Clicking on the notifications makes the header disappear on IOs

Same on Android (Brave 1.37.116 ; Chromium 100.0.4896.127)
Tracim v4.1.3 build_076

**Comment by Haskaris** [comment] 2023-03-31 09:09
Since #5805 the header isn't displayed anymore (merge into the sidebar). Closing this issue since we can't reproduce it.

**Closed by Haskaris** 2023-03-31 09:09 UTC
Labels: frontend, to sort, ux, responsive
