### ISSUE TITLE
error 404 about bootstrap-4.0.0-beta.css

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2865] opened 2020-04-09 09:12 UTC
## Bug description & symptom

I can see this error in browser console (http://192.168.2.245:6543/ui):
~~~
Erreur dans les liens source : request failed with status 404
URL de la ressource : http://192.168.2.245:6543/assets/bootstrap/bootstrap-4.0.0-beta.css?token=09187b845f
URL du lien source : bootstrap.min.css.map
~~~

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] no error exist in browser console

## Context and version information

- Visible in all version of tracim

## How to reproduce

- Open browser console and refresh tracim frontend page

## Impacted components

*"unknown"*

## Extra information

**Comment by Skylsmoi** [comment] 2024-07-04 12:35
Couldn't reproduce the issue
Closing the issue

**Closed by Skylsmoi** 2024-07-04 12:35 UTC
Labels: to sort
