### ISSUE TITLE
Bug: Search and add user to a workspace with public name is confusing

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#2942] opened 2020-04-28 10:17 UTC
## Bug description & symptom

Public name user field is not unique in database. This behavior (not unique in database) is required to permit homonyms on Tracim, especially for shared Tracim like mon.tracim.fr).

But this is problematic is following cases:

- Frontend search: When want to add a member to a shared space, there is no way to differentiate homonyms in list.

- invitation endpoint: POST `/api/v2/workspaces/{workspace_id}/members` accept a `public_name` which is confusing (and may result in inviting another user)

- This api permit to give `public_name` to search user to add to given shared space (workspace). But, as `public_name` is not unique, ~~user chosen randomly~~ will result a crash because `.one()` expect one row:

```python
    def get_one_by_public_name(self, public_name: str) -> User:
        """
        Get one user by public_name
        """
        try:
            user = self._base_query().filter(User.display_name == public_name).one()
        except NoResultFound as exc:
            raise UserDoesNotExist('User "{}" not found in database'.format(public_name)) from exc
        return user
```

## Expected

- [x] do not accept `public_name` in POST `/api/v2/workspaces/{workspace_id}/members`
    see issue #2970 and pr #2998 
- [x] fix frontend function handleClickValidateNewMember function that should use the user id instead of public_name to find the user
- [x] update interface to explicitly distinguish users with same public name (expected interfaces below) (see https://github.com/tracim/tracim/compare/fix/2942__update_search_at_add_member_to_ws)

## Impacted components

- *backend*
- *frontend*

## Extra information

Expected Interfaces:

- Members list at dashboard
![Screenshot from 2020-05-04 09-18-24](https://user-images.githubusercontent.com/35422692/80947514-97670500-8df0-11ea-9b88-10a3aef88b75.png)

- Members list at advanced dashboard
![Screenshot from 2020-04-28 13-35-32](https://user-images.githubusercontent.com/35422692/80947438-7bfbfa00-8df0-11ea-8066-ee1161003b66.png)

- Autocomplete item
![Screenshot from 2020-04-28 14-17-02](https://user-images.githubusercontent.com/35422692/80947402-671f6680-8df0-11ea-9aa6-12675a8e71c0.png)

**Comment by lebouquetin** [comment] 2020-04-28 11:32
The issue is not about having duplicated public names. As we add a unique username, there is no need to make public name unique or distinguishable - the way to distinguish is username and will be avatar (as soon as in it implemented) and user_id.

```
def get_one_by_public_name(self, public_name: str) -> User:
    [...]
```

In which case is this method used? Having a method which may return two entities when searching for one is not a problem by itself - but the error case should be managed explicitly.

The endpoint `/api/v2/workspaces/{workspace_id}/members` is not a search endpoint but a list, I'm not sure this is the endpoint related to the `get_one_by_public_name() ` unexpected exception.

Could you clarify what part of the REST API is directly concerned?

**Comment by lebouquetin** [comment] 2020-04-28 11:34
My point of view is we should show more information on the user interface in order to allow the user to distinguish two users with same public name (showing id, part of email, or probably username now). 

I think we should not have a REST API which expect to return one user only according to its public name (APIs should be based on `username` now or `user_id`)

**Comment by gbonaspetti** [comment] 2020-04-28 11:39
After a bit of searching, the problem in the frontend is in the handleClickValidateNewMember function that should use the user id instead of public_name to find the user. 

Regarding the interface, I suggest that we use the username (added on the front in ticket #2930) instead of public_name in autocomplete and put both in the list of members. For example:
![Screenshot from 2020-04-28 13-35-32](https://user-images.githubusercontent.com/35422692/80483058-9ef05f00-8955-11ea-9f01-2788bf398603.png)

**Comment by lebouquetin** [comment] 2020-04-28 12:08
@gbonaspetti I think the autocomplete can search for both `username`, `public name` and `email` ; this will work if the UI show public_name and username like in your screenshot suggestion *and* in autocomplete results listing.

Do you agree with this?

**Comment by buxx** [comment] 2020-04-28 12:19
@lebouquetin 

> In which case is this method used? Having a method which may return two entities when searching for one is not a problem by itself - but the error case should be managed explicitly.

This method is (only) used in `/api/v2/workspaces/{workspace_id}/members` POST endpoint which allow to add a user to workspace by giving `public_name`. I added `POST` method in issue description.

> I think we should not have a REST API which expect to return one user only according to its public name (APIs should be based on username now or user_id)

I agree. So, i suggest removing `user_public_name` to  POST `/api/v2/workspaces/{workspace_id}/members`.

To complete this backend change, i a agree with [giulia comment](https://github.com/tracim/tracim/issues/2942#issuecomment-620552568)

@lebouquetin @gbonaspetti @Skylsmoi @metzgegu @inkhey Do we are ok about this ? If yes, i update the issue description to add implementation choice. And add this issue to Tracim 3.0.0 project.

**Comment by gbonaspetti** [comment] 2020-04-28 12:24
I agree that autocomplete should search by name, username and email. As for the UI I am divided, I considered a lot of information for autocomplete to put the name and username, but I did two tests:
One with a smaller font for the username and the other with the smaller and lighter font.

![Screenshot from 2020-04-28 14-17-02](https://user-images.githubusercontent.com/35422692/80486588-b6cae180-895b-11ea-9280-c5e11566b792.png)

I think I like the first option better, is more readable, what about you?

**Comment by lebouquetin** [comment] 2020-04-28 12:28
@gbonaspetti I personnaly prefer the second one which make automatically more distinction between the two lines.

**Comment by gbonaspetti** [comment] 2020-04-28 12:39
> @gbonaspetti I personnaly prefer the second one which make automatically more distinction between the two lines. What about highlighting the part that match? Eg yellow background behind parts of text that match what the user typed?

I prefer without the highlight because the interface gets cleaner and I don't think it helps the user that much.
Another problem would be that when searching for something that matches the email, in the interface it would look like it has nothing in common...

**Comment by buxx** [comment] 2020-04-28 12:50
@lebouquetin About https://github.com/tracim/tracim/issues/2942#issuecomment-620569996 , solution is accepted ?

**Comment by gbonaspetti** [comment] 2020-04-30 14:37
On the dashboard the member list has a slightly different design than the advanced dashboard, since it is not possible to change the role there. Here are some suggestions on how to add the username on the interface to the dashboard. Which one do you prefer?

1. 
![Screenshot from 2020-04-30 16-23-16](https://user-images.githubusercontent.com/35422692/80723127-840e1e00-8b00-11ea-98b3-4ff33fccd27c.png)

2. 
![Screenshot from 2020-04-30 16-26-09](https://user-images.githubusercontent.com/35422692/80723132-84a6b480-8b00-11ea-93ba-5f2d6df9713c.png)

3.  
![Screenshot from 2020-04-30 16-29-36](https://user-images.githubusercontent.com/35422692/80723135-853f4b00-8b00-11ea-8ab2-87149e0c1e13.png)

**Comment by lebouquetin** [comment] 2020-05-04 07:13
@gbonaspetti I suggest:

```
Admin - Shared space manager
@admin 
```
The widget must have the same design (two lines) on all screens, I think.

**Comment by lebouquetin** [comment] 2020-05-04 07:17
@buxx giving a public_name does not make it as the unique key. See API: https://algoo.tracim.fr/api/v2/doc/#/Workspaces_%3E_Members/post_api_v2_workspaces__workspace_id__members

I do not understand why you want to remove `user_public_name` from the POST API...

**Comment by celiamgtt** [comment] 2020-05-04 07:19
The third option is nice!

**Comment by lebouquetin** [comment] 2020-05-04 07:21
@gbonaspetti @celiamgtt I think we should match with the principle`same information at same place` for all screens.

**Comment by gbonaspetti** [comment] 2020-05-04 07:24
> @gbonaspetti I suggest:
> 
> ```
> Admin - Shared space manager
> @admin 
> ```
> 
> The widget must have the same design (two lines) on all screens, I think.

I totally agree that we should maintain the two-line design and the username always after the full name.

![Screenshot from 2020-05-04 09-18-24](https://user-images.githubusercontent.com/35422692/80943953-b792c600-8de8-11ea-872b-4f91ddf67c17.png)

@lebouquetin @celiamgtt Do you approve this design?

**Comment by lebouquetin** [comment] 2020-05-04 08:01
@buxx after our visioconf, I agree with you:

- `public_name` has no meaning in this endpoint
- adding a user as shared space member must be based on `user_id`
- `email_address` should be for user creation only (in case the user does not exist yet, the process should be first to create user, then to add it as a member by based on its `user_id`

**Comment by lebouquetin** [comment] 2020-05-04 08:07
@gbonaspetti I approve your last design. @celiamgtt are you ok with this?

@gbonaspetti when design is validated, I'd like you to put all new designs capture in the issue description, so that anybody looking at the issue will understand how it works now (and all developer: what must be done / what has been done)

**Comment by buxx** [comment] 2020-05-04 08:16
I open this issue: https://github.com/tracim/tracim/issues/2970 When all todo issues opened, please link them together and close this discussion issue.

**Comment by gbonaspetti** [comment] 2020-05-04 08:58
> I open this issue: #2970 When all todo issues opened, please link them together and close this discussion issue.

@buxx Since I had already started frontend development on branch `fix/2942__update_search_at_add_member_to_ws` that points to this issue, I'd rather not create a new issue and a new branch for it (that will contain exactly the same information), so I'll close this issue once the future PR of my branch has gone through all the flow and you have done all the backend issues, if that's ok for you.

**Comment by Skylsmoi** [comment] 2020-05-04 08:59
just read this conversation and, just to be sure:
The use of public_name in the POST /members endpoint was to allow to invite users that "we don't know about" (eg. users that are not "known members". Which are users in different workspace).

If we remove the public_name, this feature must still be possible with the username:
- inviting a member to a workspace
- typing it's username
- click on the autocomplete popup "I know this user exists"

**Comment by raphj** [comment] 2020-05-06 12:06
Should we add a username field to this endpoint or this is unnecessary?

**Comment by raphj** [comment] 2020-05-07 08:57
> ensure adding a member is always based on user_id

Is it ok to allow adding my email too, since it is unique ?

**Comment by Skylsmoi** [comment] 2020-05-07 09:23
> Should we add a username field to this endpoint or this is unnecessary?

I think yes, the endpoint should return the username to allow the autocompletion

> Is it ok to allow adding users to a workspace by email too, since it is unique ?

It should be yes, with the autocomplete popup saying "Send an invitational email to this user" if he isn't a known member. If he is, the use should be shown in the autocomplete popup

**Comment by Skylsmoi** [comment] 2020-05-07 11:06
I don't think it changes anything.


>     * adding a user as shared space member must be based on `user_id`
This will block users from inviting unknown members

**Comment by raphj** [comment] 2020-05-07 11:15
So, about these two points, after discussion with @buxx and @inkhey.

> - ensure adding a member is always based on user_id

I understand that the intention behind this requirement is: we should not be able to add a member by their public name. But we still should allow adding a member by its id, username or email. Is it correct?

> - accept email only if the POST /api/v2/workspaces/{workspace_id}/members is in charge of user creation when invitation done by a trusted user

If we understand correctly, this point means that:
 - only some users should be allowed to invite users that are not yet registered on the Tracim instance by email.
 - and more specifically, only trusted users should be able to do so.

Currently, there is already a check for this. However, allowed users are not necessarily trusted users.  Allowed users are those defined by the setting `NEW_USER__INVITATION__MINIMAL_PROFILE`, which is set to TRUSTED_USER by default.
I think we should leave this unchanged.

What do you think?

@lebouquetin

**Comment by lebouquetin** [comment] 2020-05-07 11:39
How to identify a user?

- by `public_name` is not reliable because several users can have the same public name
- by `username` is almost ok but `username` may change during the life of a user
- by `email` is almost ok but `email` may change during the life of a user
- by `user_id` is the *only* way to be sure to process the expected user

- Inviting a new user by email is ok - this is the only way to invite external user
- inviting an existing user by email or by username is buggy *by design*:

    1. you search for a user and find @lebouquetin (through a GET request)
    2. before you validate the invitation I change my `username`
    3. you validate (POST request) and get an error.

If you use `user_id` for the POST, you *avoid an error* and **it's at no development extra cost** to implement.

I expect you to have this kind of forecast: are there side effects that I can avoid at no cost? At small cost?

By the way if you have a unique way to add an existing user, its better:

- less execution paths
- less bugs
- easier to understand.

So we must accept two ways to invite a user (this is about POST API):

- by email for new users
- by user_id for existing users.

All other options are ok for search / auto-complete step but not for effetivly adding a user. (this way to view the point is ok because you always get the user_id through the auto-complete step).

@gbonaspetti @metzgegu @raphj @Skylsmoi @buxx @grignards @inkhey, if you disagree, if you do not understand, if you think its overkill, we must have a talk.

Writting code that can't be buggy *by design* MUST ALWAYS be the choice compared to code that may in some rare cases be buggy (even if the probability is very very low). The only reason for writting code buggy by design is if the cost is too high.

**Comment by inkhey** [comment] 2020-05-07 12:10
> How to identify a user?
> 
>     * by `public_name` is not reliable because several users can have the same public name
> 
>     * by `username` is almost ok but `username` may change during the life of a user
> 
>     * by `email` is almost ok but `email` may change during the life of a user
> 
>     * by `user_id` is the _only_ way to be sure to process the expected user
> 
>     * Inviting a new user by email is ok - this is the only way to invite external user
> 
>     * inviting an existing user by email or by username is buggy _by design_:
>       
>       1. you search for a user and find @lebouquetin (through a GET request)
>       2. before you validate the invitation I change my `username`
>       3. you validate (POST request) and get an error.
> 
> 
> If you use `user_id` for the POST, you _avoid an error_ and **it's at no development extra cost** to implement.
> 
> I expect you to have this kind of forecast: are there side effects that I can avoid at no cost? At small cost?
> 
> By the way if you have a unique way to add an existing user, its better:
> 
>     * less execution paths
> 
>     * less bugs
> 
>     * easier to understand.
> 
> 
> So we must accept two ways to invite a user (this is about POST API):
> 
>     * by email for new users
> 
>     * by user_id for existing users.
> 
> 
> All other options are ok for search / auto-complete step but not for effetivly adding a user. (this way to view the point is ok because you always get the user_id through the auto-complete step).
> 
> @gbonaspetti @metzgegu @raphj @Skylsmoi @buxx @grignards @inkhey, if you disagree, if you do not understand, if you think its overkill, we must have a talk.
> 
> Writting code that can't be buggy _by design_ MUST ALWAYS be the choice compared to code that may in some rare cases be buggy (even if the probability is very very low). The only reason for writting code buggy by design is if the cost is too high.

Behavior seems to me still unclear in some specific cases:
- Should email be usable to had existing user ? What should be the behavior is we do add email which is already used ?
- Should endpoint do work to add user_id for a user that we do not known ?
- With this decision the mecanism "i know this user exist" will have to be removed, and there is no way to add an user that exist in instance but is not visible (because tracim is configured in a way that we see only user that are in our workspace)

I think we clearly can decide to drop the "I know this user exist" mecanism and support email here only for "new user" (so disabled for some user if they don't have the correct right), but this drop an existing functionality from tracim.

This case is not relevant from montracim as in montracim, there is, as far i remember, no filtering on know_user and all user have higher profile (trusted user) which mean they do have right to add new user by email.

**Comment by inkhey** [comment] 2020-05-28 15:29
@raphj which part of this should be done in Tracim 3.0, which part should be done in https://github.com/tracim/tracim/issues/3013 ?

**Comment by raphj** [comment] 2020-06-04 12:07
> accept email only if the POST  `/api/v2/workspaces/{workspace_id}/members` is in charge of user creation when invitation done by a trusted user

This needs clarification. I am moving this to #3013.

**Comment by Skylsmoi** [comment] 2020-06-05 13:59
I'm having an issue on the branch:
- I'm trying to invite an **unkonwn member** to a workspace
- `user3@user3.user3` exists and is not part of the workspace `ttest`
- I click the popup "I know this user exist"
- I select a role and click validate
- I'm having a flash message "user unknown" but I don't see any request sent to the backend

![Capture d’écran de 2020-06-05 15-58-35](https://user-images.githubusercontent.com/11177014/83884639-72deaf80-a745-11ea-85a1-5dcf6191d945.png)

**Comment by inkhey** [comment] 2020-06-09 13:14
verified on branch

**Closed** 2020-06-09 13:19 UTC
Labels: UX, backend, frontend, verified
