### ISSUE TITLE
API error but no notification on user interface

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1360] opened 2019-01-23 23:31 UTC
Currently, if I modify the label of a thread but enter a wrong value, the API return a 400 but the user interface tells nothing to the user.

Expected: show a message to the user when API result in an error.

How to reproduce:

- create thread entitled "discussion" in a folder
- create another thread entitle "discussion2" in the same folder
- edit "discussion2" and rename it to "discussion" => HTTP 400 but no message

Note: I think this issue is on all content types

**Comment by lebouquetin** [comment] 2019-01-23 23:32
@Skylsmoi we already talked about always showing a message to the user in case of API error. This case should not exist anymore! I do not understand how it can still exist (we talked about a generic handled showing a message)

**Comment by Skylsmoi** [comment] 2019-02-07 13:27
note for testing:
The fix has been applied the 3 apps HtmlDoc, Thread and File

**Comment by PhilippeAccorsi** [comment] 2019-02-07 17:45
@lebouquetin @Skylsmoi when flash message appear after try to edit label, form for edit label is closed. But if you clic on edit again, you not seen the good label, you see the new name you are try.

Its a problem or not? If you close and open again this content, the label is the good one. I think its a refresh problem, but I d'ont know if its difficult to solve and/or if its necessary for 2.1

**Comment by Skylsmoi** [comment] 2019-02-08 09:48
About generic handling of errors:
The generic fetch wrapper of frontend_lib will:
- handle every http status 2xx and 3xx as success code
- let the handling of any 4xx to the specific end point handler
  - the specific endpoint handler will handle the 4xx specifically regarding the response error code (in the json)
  - the specific endpoint handler will handle any unhandled 4xx error code
- handle every http status 5xx as a generic error
- handle any other http status with a msg telling user that something unexpected happend

:bulb: Be advised that there is some technical dept of old specific endpoint that uses Promises instead of async functions that wont handle unhandled 4xx error code

**Comment by Skylsmoi** [comment] 2019-02-08 10:05
@PhilippeAccorsi I will fix that, it's not a bug but it might not be the best user experience

**Comment by PhilippeAccorsi** [comment] 2019-02-08 10:13
ok.

**Comment by PhilippeAccorsi** [comment] 2019-02-08 14:47
Verified.

**Closed by PhilippeAccorsi** 2019-02-08 14:47 UTC
Labels: UX, blocker, frontend, verified
