### ISSUE TITLE
Bug: the recent activity page not show any result

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4868] opened 2021-08-19 13:14 UTC
## Description and expectations

A user can't seen anything in recent activity page of his Tracim instance. When he look inside devtool console, he can see some error 400 about 4 contents. When we look in Tracil log, we can seen error like that:

```
2021-08-19 12:29:27 INFO  [hapic:214][b'uWSGIWorker4Core1'] Exception ContentNotFound occured, return 400 http_code : Content "755" not found in database
2021-08-19 12:29:27 DEBUG [hapic:217][b'uWSGIWorker4Core1'] Traceback (most recent call last):
  File "./tracim_backend/lib/core/content.py", line 651, in get_one
    content = base_request.one()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3468, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/views/core_api/workspace_controller.py", line 627, in get_content_path
    workspace=request.current_workspace,
  File "./tracim_backend/lib/core/content.py", line 658, in get_one
    raise ContentNotFound('Content "{}" not found in database'.format(content_id)) from exc
tracim_backend.exceptions.ContentNotFound: Content "755" not found in database
```
If I remember correctly, sometime tracim try to open a comment and not a content in recent activity (I'm not really sure about that).

### How to reproduce

I don't really know but many user on different Tracim instance can seen problem like that.

### Version information

- Tracim version: 3.8.2
- Web browser: ~
- Version: ~
- Device / System: ~

## Screenshots

![recent_activity_not_loaded](https://user-images.githubusercontent.com/25848257/130074262-dc1e44f3-0f56-4b88-abf7-83ef1c8ca37a.png)

________________________________________________

**Comment by gbonaspetti** [comment] 2021-08-19 13:26
Extra information: I have the same issue, but in the recent activities of a particularly space:
- the error has the space id of my space but the content id of a content from another space (i'm a member of both)

**Comment by raphj** [comment] 2021-08-25 10:08
This bug was caused by a server misconfiguration. Closing, @PhilippeAccorsi.

**Closed by raphj** 2021-08-25 10:08 UTC
Labels: p0
