### ISSUE TITLE
Impossible to move a file to the root of a workspace

### ISSUE THREAD

**Issue by YannickBiet** [tracim/tracim#2968] opened 2020-05-02 10:20 UTC
## Bug description & symptom

Accidently a file has been moved from the root folder of my workspace to a subdirectory
I don't see any possibility using Web UI to move it back

## Screenshots

<img width="658" alt="moveBack" src="https://user-images.githubusercontent.com/930391/80861380-7bd3f100-8c6e-11ea-97d1-32129129c8df.png">

![bug](https://user-images.githubusercontent.com/930391/80861471-0b799f80-8c6f-11ea-8c55-1811e31fdb8f.gif)

## Impacted components
- *frontend*

**Comment by YannickBiet** [comment] 2020-05-02 10:21
Webdav is not an option until MACOS will be fully supported : 
https://github.com/tracim/tracim/issues/2966

**Comment by lebouquetin** [comment] 2020-05-03 22:56
@YannickBiet You can move the file to the shared space on the left panel. This is counter intuitive (we had a talk about this a few month ago). See https://github.com/tracim/tracim/issues/2468

Note: #2468 is not complete as the result of our last chat about where to move is not written in the comments (see my last comment).

**Comment by YannickBiet** [comment] 2020-05-04 16:31
Sorry @lebouquetin i dind't find the open issue. I think you can close this one to don't have duplicates in the open cases folder.
hanks for letting me know the workaround by the way !

**Comment by Haskaris** [comment] 2022-12-16 10:09
Duplicate of #2468

**Closed by Haskaris** 2022-12-16 10:09 UTC
Labels: to sort
