### ISSUE TITLE
Bug: Deleting a comment generates a "X has commented in Y" notification

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4933] opened 2021-09-17 09:04 UTC
## Description and expectations

Deleting a comment generates a "X has commented in Y" notification. It should not generates any or change the text for something like "X deleted a comment in Y".

### How to reproduce

1. Go to a thread
2. Comment something
3. Delete your comment
4. In another user account, see the notifications.

### Version information

- Tracim version: v3.9
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## Prerequisites

None

**Comment by Skylsmoi** [comment] 2024-12-26 15:14
can't reproduce. Closing

**Closed by Skylsmoi** 2024-12-26 15:14 UTC
Labels: frontend, to sort, frontend-lib
