### ISSUE TITLE
Bug: external links does NOT open in new tab.

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5546] opened 2022-03-22 16:42 UTC
## Description and expectations

External links in Tracim open in new tabs when clicked on.
However in https://algoo.tracim.fr/ui/contents/58114 there is in external links that opens in the same tab. The difference with this link is that it is included in a list (<ul>)

### How to reproduce

1. Go to https://algoo.tracim.fr/ui/contents/58114 
2. Click on the  link in the message 22/03/2022  17:12:38

### Version information

- Tracim version: 4.1.3 build_073
- Web browser: Firefox
- Version: latest
- Device / System: laptop

### Screenshots

________________________________________________

## Diagnostic

The comments can be created in 2 ways: simple or advanced edition.
In simple edition links do open in a new tab, but not in advanced edition.

This is due to tinymce's configuration which is missing the required parameter: https://www.tiny.cloud/docs/plugins/opensource/link/#default_link_target

Changing this parameter will open **newly created** links in another tab. But it won't change anything for existing comments. Existing comments could be updated to add the required parameters to `<a>` but it is more time-consuming and possibly risky?

**Comment by grignards** [comment] 2022-12-16 14:12
@Relf-Algoo Do you think it is enough to only address the issue for newly created comments or should the fix also address existing comments?

**Comment by Relf-Algoo** [comment] 2022-12-16 14:15
Well, if it's possible, I think to would be better to fix previous links too. Tracim is based on the history of its contents and the use cases show that users search the archives, so…

**Comment by lebouquetin** [comment] 2022-12-16 14:57
@grignards @Relf-Algoo

**Comment by lebouquetin** [comment] 2022-12-16 15:02
By the way, migrating old content should be a command, not a database migration (it is not required for Tracim to work)

**Comment by Haskaris** [comment] 2023-01-11 11:57
Duplicate of #215?
I'm not sure to understand the bug?

**Closed** 2023-04-20 10:01 UTC
Labels: manually tested, frontend, p2
