### ISSUE TITLE
Bug: The tab key is sometimes broken when used in tinymce

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5535] opened 2022-03-21 09:39 UTC
## Description and expectations

Sometimes pressing the tab key when tinymce is used (in note/thread/comment/…) to edit a list moves the focus outside tinymce instead of changing the list to a sub-list.

Pressing the tab key in this case should always change a list to a sub-list.

### How to reproduce

1. Open a note
2. Press the tab key **before** editing it
3. Edit it and try to change a list level by pressing the tab key

### Version information

- Tracim version: 4.1.3_build_73
- Web browser: Any
- Version: not relevant
- Device / System: not relevant

## Linked PR
PR #5606 

## To testers
Be careful to test if there is any regression about chrome performance

**Comment by Haskaris** [comment] 2022-04-08 12:56
After some digging, the tab problem is hidden by the plugin problem. Somehow, if you can't press tab to indent/outdent the list, the buttons won't work too...

**Comment by Haskaris** [comment] 2022-04-08 13:16
While I was searching how to fix that, I found that if you open a note HTML, close it you fall back on list content
Then if you click on another HTML note, you get a js error in the console and the note isn't displayed.

**Comment by Skylsmoi** [comment] 2022-04-08 15:20
Research report:
The issue come from the hack in tinymceInit.js that fixes this issue #4591.
We don't have anymore details about why the bug occurs but, in the hack above, we set the content inside tinyMce not with the expected way (`$editor.setContent('...')`) but in a custom way (`$editor.contentDocument.body.appendChild('...')`). This hack makes the indent of lists to fail.

Solutions:
1) Investigate more on the tinyMce bug related to our hack and hope to fix it or workaround it
2) Remove the hack and recreate the Chrome performance issue fixed by #4591
  2.1) And find another way to workaround the performance issue
3) Since everything comes from the base64 encode for images in tinyMce, remove it and replace it with an internal Tracim mechanism
  3.1) This mechanism could be a custom tinyMce button to add images that create a Tracim content as sub content of the content we are editing
  3.2) Link the relative preview url of the subcontent as image source

**Comment by Skylsmoi** [comment] 2022-04-08 15:56
TODO short term:
- [ ] Test the solution 2
  - [ ] If it works, remove the hack for Chrome in tinymceInit.js

Later:
- Implement the solution 3

**Comment by Haskaris** [comment] 2022-04-15 14:28
After a lot of digging. Here is the steps:

1. The hack solved in #4591 doesn't seem to work anymore, so I'm going to remove it, which will fix the tab/indent issue. However we have to be sure that there is no regression (couldn't find any regression during my tests). Furthermore we got a lag on chrome (with or without the hack) when we have a big file to edit in HTML app.
2. We have to find a workaround to have quick solution about chrome performances
3. Remove the workaround to upload images without using base64. (upload images to Tracim, use URL in img src tag)

**Comment by PhilippeAccorsi** [comment] 2022-04-27 08:59
an issue need to be created for chrome problem and this new issue need to be visible in known issue of the new release.
@Skylsmoi can you create the new issue ?
@knodelle can you add this issue in the change log ?

I think it is a good idea in the changelog to inform user about what is going on with image on chrome/chromium (litle description of this issue).

**Comment by knodelle** [comment] 2022-04-27 12:22
done

**Closed by knodelle** 2022-04-27 12:22 UTC
Labels: manually tested, frontend, p0, tinymce
