### ISSUE TITLE
app: if I filter by content, when we open content the filter disappears

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#893] opened 2018-09-11 08:26 UTC
at present

If I filtered by type of content, when I open a content, the page show again all content:

Filter by type "file"
![capture d ecran de 2018-09-11 10-22-56](https://user-images.githubusercontent.com/25848257/45347722-115bd200-b5ad-11e8-9d81-fbb56d22a2c6.png)

Expected

If you filtered by content file, If you open one file, the page don't show other type of content.

**Comment by buxx** [comment] 2018-09-11 08:46
Duplicate of #891.

**Closed by buxx** 2018-09-11 08:46 UTC
Labels: To sort, bug, frontend
