### ISSUE TITLE
add user space limitation in database and in config file for default value

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2473] opened 2019-10-07 10:08 UTC
## Feature description

Free account: limitation = 2Go
Freelance account: limitation = 100Go

This 2 field can be updated by CLI command for each user we need to update value.
In config file, we can have this 2 limitation with default value.

:warning: size limitation is for **all shared space** created by user (its not a limitation for each shared space)

## Context

*Explain the why and the how of the requested feature.*

## Prerequisites

*Optional - if some other issues must be closed before the current, list them here.*

- *#xxx*
- *...*

## Impacted components

*Optional - list components which will be impacted.*

*For example:*

- *backend*
- *frontend*
- *htmldoc / file / thread app*
- *webdav*
- *...*

*If unsure, write "unknown"*

## Extra information

*Optional - Add any extra information which will be usefull for understanding and developing the feature*

**Comment by inkhey** [comment] 2019-10-07 10:10
duplicate of #2476

**Closed** 2019-10-07 10:09 UTC
Labels: backend, mandatory
