### ISSUE TITLE
Bug: sometime content is not indexed by elasticsearch (an error appear about problem with base64)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4200] opened 2021-02-19 11:14 UTC
## Description and expectations

I Have chnaged a status of a file an search not show this new version of the file. After investiguation I find error in elasticsearch log, and also in tracim log.

Tracim log error:
~~~
2021-02-19 10:19:05 INFO  [tracim:45][b'uWSGIWorker1Core1'] [ESSearchApi] Indexing content 4
2021-02-19 10:19:05 WARNI [elasticsearch:136][b'uWSGIWorker1Core1'] POST http://elasticsearch:9200/0056_branchdev-content/_doc/4?pipeline=attachment [status:500 request:0.003s]
2021-02-19 10:19:05 ERROR [tracim:54][b'uWSGIWorker1Core1'] [ESContentIndexer] Exception while indexing modified content 4
Traceback (most recent call last):
  File "./tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py", line 665, in on_content_modified
    search_api.index_content(content)
  File "./tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py", line 276, in index_content
    request_timeout=self._config.SEARCH__ELASTICSEARCH__REQUEST_TIMEOUT,
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch_dsl/document.py", line 448, in save
    **doc_meta
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 364, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 239, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/base.py", line 168, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(500, 'exception', 'java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [b64_file] not present as part of path [b64_file]')
~~~

Elasticsearch error
~~~
{"log":"{\"type\": \"server\", \"timestamp\": \"2021-02-19T10:19:05,065+0000\", \"level\": \"DEBUG\", \"component\": \"o.e.a.b.TransportBulkAction\", \"cluster.name\": \"docker-cluster\", \"node.name\": \"elasticsearch\", \"cluster.uuid\": \"CD3-EWJIT4mZkNQYkigXlQ\", \"node.id\": \"dEPc5r7CQ7Op-AOCvpMcQw\",  \"message\": \"failed to execute pipeline [attachment] for document [0056_branchdev-content/_doc/4]\" , \n","stream":"stdout","time":"2021-02-19T10:19:05.066487825Z"}
{"log":"\"stacktrace\": [\"org.elasticsearch.ElasticsearchException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [b64_file] not present as part of path [b64_file]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066514041Z"}
{"log":"\"at org.elasticsearch.ingest.CompoundProcessor.newCompoundProcessorException(CompoundProcessor.java:194) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066518417Z"}
{"log":"\"at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:133) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066521635Z"}
{"log":"\"at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:100) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066524718Z"}
{"log":"\"at org.elasticsearch.ingest.IngestService.innerExecute(IngestService.java:481) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066527623Z"}
{"log":"\"at org.elasticsearch.ingest.IngestService.access$100(IngestService.java:70) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066530501Z"}
{"log":"\"at org.elasticsearch.ingest.IngestService$4.doRun(IngestService.java:410) [elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066533392Z"}
{"log":"\"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066536292Z"}
{"log":"\"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066539599Z"}
{"log":"\"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066542581Z"}
{"log":"\"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066545388Z"}
{"log":"\"at java.lang.Thread.run(Thread.java:835) [?:?]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.06655695Z"}
{"log":"\"Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [b64_file] not present as part of path [b64_file]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066560046Z"}
{"log":"\"... 11 more\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066562792Z"}
{"log":"\"Caused by: java.lang.IllegalArgumentException: field [b64_file] not present as part of path [b64_file]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066565372Z"}
{"log":"\"at org.elasticsearch.ingest.IngestDocument.resolve(IngestDocument.java:346) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066568807Z"}
{"log":"\"at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:114) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066571463Z"}
{"log":"\"at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:131) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066574122Z"}
{"log":"\"at org.elasticsearch.ingest.IngestDocument.getFieldValueAsBytes(IngestDocument.java:177) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066576788Z"}
{"log":"\"at org.elasticsearch.ingest.attachment.AttachmentProcessor.execute(AttachmentProcessor.java:79) ~[?:?]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066579454Z"}
{"log":"\"at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:123) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066582062Z"}
{"log":"\"... 9 more\"] }\n","stream":"stdout","time":"2021-02-19T10:19:05.066584737Z"}
{"log":"{\"type\": \"server\", \"timestamp\": \"2021-02-19T10:19:05,066+0000\", \"level\": \"WARN\", \"component\": \"r.suppressed\", \"cluster.name\": \"docker-cluster\", \"node.name\": \"elasticsearch\", \"cluster.uuid\": \"CD3-EWJIT4mZkNQYkigXlQ\", \"node.id\": \"dEPc5r7CQ7Op-AOCvpMcQw\",  \"message\": \"path: /0056_branchdev-content/_doc/4, params: {pipeline=attachment, index=0056_branchdev-content, id=4}\" , \n","stream":"stdout","time":"2021-02-19T10:19:05.066953692Z"}
{"log":"\"stacktrace\": [\"org.elasticsearch.ElasticsearchException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [b64_file] not present as part of path [b64_file]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066971313Z"}
{"log":"\"at org.elasticsearch.ingest.CompoundProcessor.newCompoundProcessorException(CompoundProcessor.java:194) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066975539Z"}
{"log":"\"at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:133) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066978565Z"}
{"log":"\"at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:100) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066981309Z"}
{"log":"\"at org.elasticsearch.ingest.IngestService.innerExecute(IngestService.java:481) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066983857Z"}
{"log":"\"at org.elasticsearch.ingest.IngestService.access$100(IngestService.java:70) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066986437Z"}
{"log":"\"at org.elasticsearch.ingest.IngestService$4.doRun(IngestService.java:410) [elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066989055Z"}
{"log":"\"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066991683Z"}
{"log":"\"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.066994403Z"}
{"log":"\"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067004681Z"}
{"log":"\"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067007686Z"}
{"log":"\"at java.lang.Thread.run(Thread.java:835) [?:?]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067010305Z"}
{"log":"\"Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [b64_file] not present as part of path [b64_file]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067012877Z"}
{"log":"\"... 11 more\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067015593Z"}
{"log":"\"Caused by: java.lang.IllegalArgumentException: field [b64_file] not present as part of path [b64_file]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067018212Z"}
{"log":"\"at org.elasticsearch.ingest.IngestDocument.resolve(IngestDocument.java:346) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067021648Z"}
{"log":"\"at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:114) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067024366Z"}
{"log":"\"at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:131) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067026954Z"}
{"log":"\"at org.elasticsearch.ingest.IngestDocument.getFieldValueAsBytes(IngestDocument.java:177) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067029561Z"}
{"log":"\"at org.elasticsearch.ingest.attachment.AttachmentProcessor.execute(AttachmentProcessor.java:79) ~[?:?]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067032164Z"}
{"log":"\"at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:123) ~[elasticsearch-7.0.0.jar:7.0.0]\",\n","stream":"stdout","time":"2021-02-19T10:19:05.067034777Z"}
{"log":"\"... 9 more\"] }\n","stream":"stdout","time":"2021-02-19T10:19:05.067037419Z"}
~~~

### How to reproduce

I don't know

### Version information

- Tracim version: all Tracim version (detected on `3.5.0_build_038` but also on `3.5.0`)

## Screenshots

________________________________________________

**Comment by grignards** [comment] 2021-02-19 15:04
Difficult to reproduce, giving a `b64_file=None` to elasticsearch recreates the error artificially.

**Comment by PhilippeAccorsi** [comment] 2021-02-19 15:39
I think we can add this issue to the same project and check if issue #4149 solved this bug or not.
Are you agree with that ?

**Comment by grignards** [comment] 2021-02-19 15:46
> I think we can add this issue to the same project and check if issue #4149 solved this bug or not.
> Are you agree with that ?

That's fine for me.

**Comment by PhilippeAccorsi** [comment] 2021-03-02 15:23
I have tested to reproduce this error on the same server with the same file but I can't reproduce this.

I also never seen log like this one `2021-02-19 10:19:05 INFO  [tracim:45][b'uWSGIWorker1Core1'] [ESSearchApi] Indexing content 4` when I add content or replace content.
I not known what is necessary to shown this log. Maybe its the reason why I can't reproduce this error (if tracim is not in the same context)

**Comment by inkhey** [comment] 2021-03-02 15:27
> I have tested to reproduce this error on the same server with the same file (in another space) but I can't reproduce this.
> 
> I also never seen log like this one `2021-02-19 10:19:05 INFO [tracim:45][b'uWSGIWorker1Core1'] [ESSearchApi] Indexing content 4` when I add content or replace content.
> I not known what is necessary to shown this log. Maybe its the reason why I can't reproduce this error (if tracim is not in the same context)

Tried some things. Cannot reproduce the error with data given. I do get the log but failed to get the issues.

**Comment by inkhey** [comment] 2021-03-03 09:53
We should now wait to experience (or not) this issue in newer version before take much time trying to reproduce it as it's unclear what is the reason behind the bug and if new code will fix it.

**Comment by inkhey** [comment] 2021-03-04 09:35
Found an indexation issue related to asynchronous indexing mode: command line indexing doesn't work if jobs processing mode is async.

**Comment by inkhey** [comment] 2021-03-24 09:11
As we do not reproduce this issue since the last fixes, i thought we can close it.

**Closed by inkhey** 2021-03-24 09:11 UTC
Labels: backend, blocked by reporter, bug, search
