### ISSUE TITLE
mail_fetcher is broken since modification in CFG

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1676] opened 2019-05-03 14:47 UTC
## Bug description & symptom

Email_fetcher not working. 
~~~
Traceback (most recent call last):
  File "/tracim/backend/daemons/mail_fetcher.py", line 18, in <module>
    daemon.run()
  File "/tracim/backend/tracim_backend/lib/mail_fetcher/daemon.py", line 41, in run
    folder=self.config.EMAIL_REPLY__IMAP__FOLDER,
AttributeError: 'CFG' object has no attribute 'EMAIL_REPLY__IMAP__FOLDER'
~~~

## Diagnostic

Some parameter in /backend/tracim_backend/lib/mail_fetcher/daemon.py have not correct syntaxes

## Expected

- [ ] for each `.` in development.ini we need to have `__` in daemon.py

## Impacted components

- *backend*

**Comment by lebouquetin** [comment] 2019-05-03 14:52
@inkhey what is the way to test that config is not broken silently anymore?

**Comment by PhilippeAccorsi** [comment] 2019-05-03 16:01
- [ ] Create specific test for this kind of regression (test reply_by_email and if some parameter is not write correctly in code).

**Comment by lebouquetin** [comment] 2019-05-06 22:30
The fix has been merged but the regression test must be implemented for 2.3 release.

**Comment by inkhey** [comment] 2019-06-04 10:17
@PhilippeAccorsi @lebouquetin Creation of regression test here is unclear. It's complicated to run functionnal test on mail fetcher because we do not have found any easy solution to mock imap (mailhog is only smtp).
Code broken is place is a specific place just before launching deamon, should i have a test running daemon with bad value (not valid imap) and then stop it ?

**Comment by lebouquetin** [comment] 2019-06-07 15:24
The test is not about  mail fetcher working correctly but about parameter naming which is the one used in the code

**Comment by basilelegal** [comment] 2019-06-10 09:18
@PhilippeAccorsi I need some informations to reproduce.

**Comment by inkhey** [comment] 2019-06-12 14:26
to do : 
- run daemon just to check correct behaviour
- test CFG consistency, check if config parameters `whaterver` set CFG.whatever

**Comment by basilelegal** [comment] 2019-06-19 09:23
tested

**Closed by basilelegal** 2019-06-19 09:23 UTC
Labels: backend, blocker, bug, test
