### ISSUE TITLE
Long titles are not limited when we're uploading files

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2062] opened 2019-07-04 07:32 UTC
## Bug description & symptom

Long titles are not limited when we're uploading files

## Expected

Titles should be cropped.

## Screenshots

![Capture d'écran de 2019-07-03 16-44-22](https://user-images.githubusercontent.com/50453784/60647627-60296f80-9e3e-11e9-9b2a-76c3bec460fe.png)

## Impacted components

- frontend

**Comment by metzgegu** [comment] 2019-07-17 08:06
I can't reproduce the bug
![ticket1](https://user-images.githubusercontent.com/31687635/61358412-89a0bd00-a87a-11e9-8f23-89395039342b.png)

**Comment by PhilippeAccorsi** [comment] 2019-07-17 08:29
Tested by @metzgegu on develop branch.
@celiamgtt which version of tracim do you used?

**Comment by celiamgtt** [comment] 2019-07-17 09:08
v2.3.1 with Firefox 60.8.0esr (64 bits)

**Comment by PhilippeAccorsi** [comment] 2019-07-17 10:11
Bug not exist on:
- Chrome  68.0.3440.75
- Firefox 68.0
- Chromium 75.0.3770.90
- Opera 62.0.3331.66

**Comment by metzgegu** [comment] 2019-07-17 10:13
Tested with Firefox 68.0 and Chromium Version 75.0.3770.100 (64 bits)

**Comment by PhilippeAccorsi** [comment] 2019-07-17 10:20
So I close this issue. 
This bug exists on stretch with last stable version of firefox-esr (60.8.0).

**Closed by PhilippeAccorsi** 2019-07-17 10:20 UTC
Labels: blocked by reporter, bug, frontend, unclear
