### ISSUE TITLE
A second scrollbar appears on dashboard page (macOS x Chrome)

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2766] opened 2020-03-18 12:56 UTC
## Bug description & symptom

A second scrollbar appears on dashboard page (macOS x Chrome)

## Expected

Only one scrollbar.

## Context and version information

- Desktop environment
    - macOS Catalina 10.15.1
    - Chrome Version 80.0.3987.132 (Build officiel) (64 bits)

## Screenshots

![Capture d’écran 2020-03-18 à 13 21 13](https://user-images.githubusercontent.com/50453784/76962777-1e831b00-6920-11ea-9522-64786b46cb40.png)

## Impacted components

- frontend

**Comment by Skylsmoi** [comment] 2024-12-18 10:18
Can't reproduce on tracim 4.11.1 and safari 18
Closing

**Closed by Skylsmoi** 2024-12-18 10:18 UTC
Labels: frontend, to sort, ux
