### ISSUE TITLE
Bug: blank screen when start Tracim and collaboraOnline for the first time (first load of first file)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5559] opened 2022-03-29 13:24 UTC
## Description and expectations

Each time I deploy tracim on production, I seen a blank screen when I create the first collaborative document. After ctrl + F5, all seems working correctly.
I seen also this bug on one tracim instance when I clean the existing instance (its an test instance and I clean it 3 time a day).

I not really seen error in the browser devtool, and after small investiguation with a frontend developer, we think something is not correctly pull or charge on the first start. After first ctrl+F5, all new file or the existing file works correctly.

### How to reproduce

- start new tracim (from beggining: no date, empty db, etc.)
- create first space
- create a collaborative document (first creation on this new installation)
=> tracim try to open Collabora Online, but screen stay blank (tracim header and sidebar are shown correctly)

### Version information

- Tracim version: since old version (maybe since 2 years)
- Web browser: Firefox
- Version: all version of firefox (not seems to be related
- Device / System: Debian 10-11 Ubuntu 18.04-20.04

### Screenshots

________________________________________________

## Extra information
Related: https://github.com/tracim/tracim/issues/4765
Related: https://github.com/tracim/tracim/issues/5598

Fixed in: https://github.com/tracim/tracim/commit/bb7a43fbd0d6e4566c1743256bd1c26caf30df58
The fix above is a frontend workaround for https://github.com/tracim/tracim/issues/5598

**Comment by inkhey** [comment] 2022-04-06 11:56
@PhilippeAccorsi I tried this one with  the "test_docker" mecanism. I didn't succeed to reproduce the issue. Maybe your environment is different in some way ?

**Comment by PhilippeAccorsi** [comment] 2022-04-07 10:15
What is `the "test_docker" mecanism` ?

> Maybe your environment is different in some way

I not sure I understand this. Different between what ?

**Comment by PhilippeAccorsi** [comment] 2022-04-08 12:32
I think we need to try one new installation on production @inkhey (we can do this next week), and seen directly if the problem appear again.

One new version of Collabora Online is released today (with some change for wopi), so I think it is better to try first new tracim with new image, and if problem appear, we can seen this directly. If not, we can close issue.

**Comment by PhilippeAccorsi** [comment] 2022-04-08 12:34
Sometime I seen the error on demo installation but not seen when I tested the last 2-3 days.

**Comment by Skylsmoi** [comment] 2022-04-12 14:42
R&d report:

### To reproduce
This only is reproducible when the first user of an instance create the first space and the first content without reloading the page.

To reproduce, we have to, through tracimcli, delete the user, which will delete all its spaces and contents and then recreate the user.

### After reproducing the issue, I have checked that
- After clicking on "Validate and create" in the popup to create collaborative document
- The popup closes and nothing more happens
- In the console, we can see a `<OpenContentApp> did Update` with the location `/ui/workspaces/4/contents`
- Then a `GLOBAL_dispatchEvent redirect {url: '/ui/online_edition/workspaces/4/contents/5'}`
- Then `<Tracim> Custom event redirect {url: '/ui/online_edition/workspaces/4/contents/5'}`
- Then `GLOBAL_dispatchEvent unmount_app undefined`

After that, we are supposed to see the log for app file unmounting and the `GLOBAL_renderAppFullscreen` for app collaborative document.

Since we don't see the `GLOBAL_renderAppFullscreen` log, I suspect the frontend router to not properly redirect the frontend app.

**Comment by Skylsmoi** [comment] 2022-04-13 10:29
after more investigations, the issue has been fixed here https://github.com/tracim/tracim/commit/bb7a43fbd0d6e4566c1743256bd1c26caf30df58

The issue exists on release build but not on develop.

It came from the backend not sending TLM is the right order which force the frontend to put a workaround for it

**Comment by Skylsmoi** [comment] 2022-04-13 13:39
Since the issue is fixed by the workaround (see extra information) this issue in not reproducible. I'm closing it
Note that `release_04.01.03` doesn't have the fix

**Closed by Skylsmoi** 2022-04-13 13:39 UTC
Labels: frontend, app-collaborative, p0
