### ISSUE TITLE
Move content at workspace root

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#2013] opened 2019-06-25 09:06 UTC
## Feature description

Improve user experience when try to move a content from folder to workspace root.

## Context

To move a content in its workspace root, content must be dropped in its workspace in sidebar.

## Prerequisites

none

## Impacted components

* frontend

## Extra information

none

**Comment by Skylsmoi** [comment] 2021-06-25 14:25
this is a duplicate of https://github.com/tracim/tracim/issues/2468
I'm closing this issue

**Closed by Skylsmoi** 2021-06-25 14:25 UTC
Labels: enhancement, frontend, to sort
