### ISSUE TITLE
Error message for uploading an existing file isn't explicit enough

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2786] opened 2020-03-25 15:13 UTC
## Bug description & symptom

When the user tries to upload a file already existing in a folder, the error message 'Some file(s) couldn't be uploaded' is displayed. There is a tooltip on the warning icon next to the file name telling: 'a content with the same name already exists'. It's an important information, it should be more visible.

## Expected

Warning message should be more specific or a specific message should appear next to the file.

## Screenshots

Error message
![Capture d’écran 2020-03-25 à 15 12 27](https://user-images.githubusercontent.com/50453784/77551920-2eb47080-6eb3-11ea-8a79-f42e2e611fea.png)

Error tooltip
<img width="1279" alt="Capture d’écran 2020-03-25 à 15 51 46" src="https://user-images.githubusercontent.com/50453784/77551978-3f64e680-6eb3-11ea-8b8f-984e4dffcb42.png">

## Impacted components

- frontend

**Comment by Skylsmoi** [comment] 2024-12-18 09:57
The message is now explicit.
Can't reproduce.
Closing

**Closed by Skylsmoi** 2024-12-18 09:57 UTC
Labels: frontend, to sort, ux
